import type { Question } from '../../types';

/**
 * Selección editorial de preguntas avanzadas que complementan la cobertura
 * actual de los módulos AWS de identidad, datos, operación y arquitectura.
 */
export const awsGuideSeniorCandidates: Question[] = [
  {
    id: 'aws-guide-senior-cognito-resource-server',
    unitId: 27,
    lessonId: 'aws-u27-l1',
    prompt: '¿Cómo conectarías Spring Security con tokens de Cognito?',
    shortAnswer: 'Validaría el token como resource server y autorizaría con los claims y scopes esperados para ese tipo de token.',
    answer: 'Configuro Spring Security como OAuth 2.0 resource server para validar firma, emisor y vigencia usando las claves públicas del user pool. Después autorizo con scopes o claims permitidos y verifico que el token sea del tipo esperado: en Cognito, `client_id` y `aud` no se aplican igual en todos los tipos y configuraciones. La validación del JWT tampoco demuestra que la persona sea dueña del pedido; esa regla sigue en la aplicación.',
    keyPoints: ['validar firma, emisor y vigencia', 'distinguir tipo y claims del token Cognito', 'comprobar autorización del recurso en la aplicación'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-cloudfront-private-cache',
    unitId: 29,
    lessonId: 'aws-u29-l3',
    prompt: '¿Cómo evitarías que CloudFront entregue el perfil de un usuario a otro?',
    shortAnswer: 'Evitaría compartir en caché respuestas privadas entre identidades y definiría claves y políticas de caché según el contenido.',
    answer: 'Separaría contenido público cacheable, como imágenes con claves versionadas, de respuestas personalizadas. Para datos privados deshabilitaría la caché compartida o configuraría explícitamente la clave y el comportamiento de caché para que no se reutilice una respuesta entre usuarios. También revisaría headers, cookies, query strings, autorización en el origen y respuestas de error. La autenticación del origen no corrige una política que mezcla respuestas en el edge.',
    keyPoints: ['separar contenido público y privado', 'evitar compartir respuestas entre identidades', 'revisar clave y política de caché'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-multitenant-isolation',
    unitId: 27,
    lessonId: 'aws-u27-l1',
    prompt: '¿Cómo diseñarías aislamiento multi-tenant entre React, Spring y almacenamiento AWS?',
    shortAnswer: 'La API derivaría el tenant de una identidad autenticada y aplicaría ese alcance en cada consulta y acceso a objetos.',
    answer: 'React puede enviar contexto de tenant para seleccionar una vista, pero no es una autoridad confiable. Spring obtiene el tenant de claims verificados o de una relación de membresía y lo aplica a cada operación, consulta y clave de objeto. En AWS limitaría los roles y políticas a las acciones requeridas; cuando el acceso directo a S3 sea necesario, emitiría URLs temporales para una clave validada por el backend. Probaría intentos de cambiar el tenant o el ID de objeto en la petición.',
    keyPoints: ['derivar identidad del tenant desde fuente confiable', 'aplicar alcance en todas las lecturas y escrituras', 'limitar acceso S3 y probar cruces entre tenants'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-jwt-revocation',
    unitId: 27,
    lessonId: 'aws-u27-l2',
    prompt: '¿Cómo revocarías acceso inmediato si Java valida JWT localmente?',
    shortAnswer: 'Un JWT ya emitido puede seguir siendo válido hasta expirar; para revocación rápida agregaría una comprobación de estado o acortaría la ventana de validez.',
    answer: 'La validación local comprueba firma y claims sin consultar al emisor en cada petición, así que una revocación puede no propagarse hasta la expiración del token. Primero definiría qué significa “inmediato” para el riesgo y la latencia aceptable. Las opciones incluyen tokens de vida corta con renovación controlada, una lista de revocación o una comprobación de sesión para operaciones sensibles. Cada comprobación remota agrega dependencia y debe fallar de forma explícita y medible.',
    keyPoints: ['JWT local no consulta revocación por petición', 'elegir ventana de expiración según riesgo', 'valorar lista o estado remoto para revocación rápida'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-realtime-multiple-tasks',
    unitId: 35,
    lessonId: 'aws-u35-l2',
    prompt: '¿Cómo escalarías notificaciones en tiempo real con varias tareas Spring?',
    shortAnswer: 'Usaría un canal compartido o un servicio administrado porque la memoria de una tarea no distribuye eventos a las demás.',
    answer: 'Una conexión WebSocket o SSE queda asociada a una tarea, así que publicar el evento sólo en memoria no llega a clientes conectados a otras réplicas. Usaría un broker o servicio de conexiones compartido, con autenticación y autorización de suscripciones por usuario o tenant. El cliente debe reconectar, deduplicar y poder recuperar eventos desde un cursor o snapshot. Las sesiones pegajosas pueden mantener una conexión en una tarea, pero no distribuyen eventos ni recuperan los perdidos tras una caída.',
    keyPoints: ['estado en memoria no se comparte entre tareas', 'distribuir eventos mediante canal compartido', 'diseñar reconexión y recuperación del cliente'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-rds-proxy',
    unitId: 30,
    lessonId: 'aws-u30-l1',
    prompt: '¿Cuándo RDS Proxy ayuda y cuándo no resuelve el problema?',
    shortAnswer: 'Puede reducir la presión de conexiones mediante reutilización, pero no arregla consultas lentas, locks ni transacciones largas.',
    answer: 'Lo evaluaría cuando muchas conexiones de clientes de vida corta o cargas variables presionan el límite de conexiones de RDS. Mediría conexiones activas, espera del pool y latencia antes y después. Revisaría el motor y el estado de sesión: ciertas operaciones o transacciones pueden fijar una conexión al cliente y reducir la multiplexación. Coordinaría el tamaño del pool de Spring con las tareas ECS; el proxy no sustituye optimizar consultas ni dimensionar la base.',
    keyPoints: ['útil ante presión de conexiones', 'no corrige consultas, locks o transacciones largas', 'medir pinning y coordinar con el pool de Spring'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-dynamodb-hot-partition',
    unitId: 30,
    lessonId: 'aws-u30-l2',
    prompt: '¿Qué revisarías si DynamoDB limita solicitudes aunque la carga total parezca baja?',
    shortAnswer: 'Buscaría concentración de tráfico en claves o índices calientes, porque el promedio total puede ocultar una partición saturada.',
    answer: 'Revisaría métricas de throttling, consumo por operación e índices, y segmentaría por clave o tenant para localizar concentración. Una partition key muy popular puede limitar solicitudes aun cuando el total de la tabla parezca moderado. Cambiaría el modelo para distribuir las escrituras sólo si puedo explicar cómo recuperar y agregar los datos; añadir sufijos aleatorios sin diseñar las lecturas traslada el problema. Validaría la distribución con una carga representativa.',
    keyPoints: ['inspeccionar throttling por tabla e índice', 'buscar claves calientes y concentración por tenant', 'rediseñar claves junto con la estrategia de lectura'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-expand-contract',
    unitId: 37,
    lessonId: 'aws-u37-l3',
    prompt: '¿Cómo harías un cambio de esquema incompatible sin exigir una actualización instantánea?',
    shortAnswer: 'Aplicaría expand/contract para que versiones viejas y nuevas del servicio convivan durante la migración.',
    answer: 'Primero agregaría la estructura nueva sin retirar la anterior. Desplegaría código que pueda leer ambas formas y escribir de manera compatible; después migraría los datos con progreso medible y verificaría todos los consumidores, incluidas pestañas React antiguas y workers. Retiraría lo viejo en una entrega posterior. Cada paso necesita una comprobación y reversión propia; un rollback de código sólo es seguro mientras el esquema siga siendo compatible.',
    keyPoints: ['expandir esquema antes de migrar', 'mantener compatibilidad durante la convivencia', 'retirar estructura vieja tras verificar consumidores'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-canary-blue-green',
    unitId: 35,
    lessonId: 'aws-u35-l2',
    prompt: '¿Cómo elegirías rolling, blue/green y canary para una entrega riesgosa?',
    shortAnswer: 'Compararía el alcance de exposición, el costo de coexistencia y la capacidad de medir el impacto antes de ampliar tráfico.',
    answer: 'Rolling reemplaza instancias gradualmente; blue/green conserva dos entornos y cambia el tráfico; canary expone una fracción y amplía si las señales son buenas. Elegiría según riesgo, posibilidad de asignar tráfico, costo y métricas disponibles. Observaría errores y resultados de negocio, además de salud de tareas. Revisaría compatibilidad del esquema y efectos externos: volver el tráfico a la versión anterior no deshace pagos, mensajes o escrituras ya ejecutadas.',
    keyPoints: ['comparar exposición, costo y observabilidad', 'mirar señales técnicas y de negocio', 'validar compatibilidad y efectos irreversibles'],
    level: 'Profundización senior',
  },
  {
    id: 'aws-guide-senior-duplicate-order-incident',
    unitId: 37,
    lessonId: 'aws-u37-l1',
    prompt: '¿Cómo conducirías un incidente donde aparecen pedidos duplicados después de un despliegue?',
    shortAnswer: 'Contendría el flujo duplicador, mediría el impacto y preservaría evidencia antes de reparar datos con reglas auditables.',
    answer: 'Determinaría alcance y detendría o limitaría el flujo que produce duplicados según la evidencia. Correlacionaría identificadores de negocio, claves idempotentes, requests y mensajes para distinguir doble envío, reintento o defecto del consumidor. Separaría mitigación de reparación: cobros e inventario requieren conciliación auditada, no borrar filas a ciegas. Tras estabilizar, agregaría una prueba que reproduzca la caída entre confirmar el efecto y completar el mensaje, y una señal que detecte duplicados temprano.',
    keyPoints: ['contener y cuantificar impacto', 'correlacionar requests, mensajes y claves idempotentes', 'conciliar datos con auditoría y prevenir recurrencia'],
    level: 'Profundización senior',
  },
];
