import type { QuizQuestion } from '../../types';
import { awsQuizzesU27U31 } from './quizzes-u27-u31';
import { awsQuizzesU32U37 } from './quizzes-u32-u37';
import { awsQuizzesU38 } from './quizzes-u38';
import { awsGuideQuizAdditions } from './quizzes-guide-additions';

const originalAwsQuizzes: QuizQuestion[] = [
  {id:'aws-quiz-u26-01',unitId:26,lessonId:'aws-u26-l1',prompt:'Una startup debe instalar un agente propio y elegir el sistema operativo. ¿Qué modelo le da ese control?',correctIndex:0,options:[{text:'IaaS: máquinas virtuales que el equipo configura.',explanation:'Correcta: IaaS entrega infraestructura y deja al equipo elegir sistema operativo, red y agente.'},{text:'PaaS: plataforma administrada para desplegar código.',explanation:'PaaS reduce operación de plataforma; sirve si no se necesita administrar el sistema operativo.'},{text:'SaaS: aplicación lista para usuarios finales.',explanation:'SaaS resuelve una necesidad de negocio terminada, no ofrece una máquina para instalar agentes.'},{text:'CloudFront: CDN para entregar contenido.',explanation:'CloudFront acelera distribución de contenido; no provee cómputo ni control del sistema operativo.'}]},
  {id:'aws-quiz-u26-02',unitId:26,lessonId:'aws-u26-l1',prompt:'Un equipo quiere publicar una API sin aplicar parches del sistema operativo. ¿Qué opción encaja?',correctIndex:1,options:[{text:'IaaS con una instancia EC2.',explanation:'EC2 daría control, pero el equipo seguiría parchando y operando el sistema.'},{text:'PaaS o servicio administrado de plataforma.',explanation:'Correcta: el proveedor opera la plataforma y el equipo se concentra en código y configuración.'},{text:'Una segunda región para la API.',explanation:'Otra región mejora aislamiento geográfico, pero no elimina tareas de plataforma.'},{text:'Una política IAM más amplia.',explanation:'IAM controla permisos; no administra parches ni runtime de la API.'}]},
  {id:'aws-quiz-u26-03',unitId:26,lessonId:'aws-u26-l1',prompt:'Un desarrollador afirma que AWS debe proteger las contraseñas que la aplicación guardó en S3. ¿Qué aclara el modelo compartido?',correctIndex:2,options:[{text:'AWS cifra automáticamente cualquier dato sin configuración.',explanation:'El cifrado puede configurarse, pero el cliente sigue definiendo acceso, clasificación y manejo de secretos.'},{text:'El cliente debe operar todos los centros de datos.',explanation:'AWS opera la infraestructura física; ese no es el deber del cliente.'},{text:'AWS protege la infraestructura; el cliente configura acceso y protege sus datos.',explanation:'Correcta: la división depende del servicio, pero identidad, permisos y contenido siguen siendo responsabilidad del cliente.'},{text:'Usar una región elimina toda obligación de seguridad.',explanation:'La región define ubicación; no reemplaza controles de identidad ni políticas de datos.'}]},
  {id:'aws-quiz-u26-04',unitId:26,lessonId:'aws-u26-l2',prompt:'Una empresa argentina debe elegir dónde residirán sus datos por requisitos legales. ¿Qué decisión evalúa primero?',correctIndex:3,options:[{text:'El tamaño de la instancia EC2.',explanation:'La capacidad define cómputo, pero no la ubicación geográfica de los datos.'},{text:'El número de consumers Kafka.',explanation:'Ese dato afecta mensajería, no residencia o jurisdicción de datos.'},{text:'La política de reintentos HTTP.',explanation:'Los reintentos influyen en resiliencia, no en dónde se almacenan los datos.'},{text:'La región AWS que cumple residencia, servicios y latencia.',explanation:'Correcta: la región fija el área geográfica y se elige considerando normativa y cercanía.'}]},
  {id:'aws-quiz-u26-05',unitId:26,lessonId:'aws-u26-l2',prompt:'Un corte eléctrico afecta un edificio. La aplicación debe seguir disponible dentro de la misma región. ¿Qué diseño ayuda?',correctIndex:0,options:[{text:'Distribuir componentes entre Availability Zones.',explanation:'Correcta: las AZ son dominios aislados; repartir componentes reduce el impacto de un único edificio.'},{text:'Duplicar el nombre del bucket S3.',explanation:'Un nombre no aporta aislamiento de cómputo ni failover de la aplicación.'},{text:'Aumentar el timeout de la API.',explanation:'Esperar más no recupera un componente que quedó fuera de servicio.'},{text:'Dar permisos de administrador al servicio.',explanation:'Más permisos no mejora disponibilidad y aumenta el riesgo de seguridad.'}]},
  {id:'aws-quiz-u26-06',unitId:26,lessonId:'aws-u26-l2',prompt:'Un sistema ya usa dos AZ, pero ambas dependen de la misma región que quedó indisponible. ¿Qué límite muestra el caso?',correctIndex:1,options:[{text:'Las AZ no permiten balanceadores.',explanation:'Los balanceadores pueden trabajar entre AZ; ese no es el límite observado.'},{text:'Multi-AZ no cubre una caída completa de región.',explanation:'Correcta: para ese riesgo se evalúa recuperación o arquitectura multi-región según RTO y costo.'},{text:'Una región contiene una sola AZ.',explanation:'Una región contiene varias AZ; justamente por eso Multi-AZ puede aislar fallos locales.'},{text:'Los datos S3 no pueden replicarse.',explanation:'S3 ofrece mecanismos de replicación; no es la causa de la dependencia regional.'}]},
  {id:'aws-quiz-u26-07',unitId:26,lessonId:'aws-u26-l2',prompt:'Usuarios de Buenos Aires notan lentitud al usar una API alojada lejos. ¿Qué criterio debe guiar la primera evaluación?',correctIndex:2,options:[{text:'Cambiar el nombre de la cuenta AWS.',explanation:'El nombre de cuenta no cambia la distancia de red ni el tiempo de respuesta.'},{text:'Crear más usuarios IAM.',explanation:'IAM resuelve identidad; no reduce el recorrido de las solicitudes.'},{text:'Medir latencia hacia regiones candidatas junto con residencia de datos.',explanation:'Correcta: la región se compara por cercanía, requisitos legales y servicios disponibles.'},{text:'Desactivar los health checks.',explanation:'Quitar health checks elimina señal operativa y no mejora la ruta de red.'}]},
  {id:'aws-quiz-u26-08',unitId:26,lessonId:'aws-u26-l3',prompt:'Antes de lanzar pagos, el equipo quiere detectar riesgos de seguridad, operación y costo. ¿Qué práctica lo estructura?',correctIndex:3,options:[{text:'Elegir el servicio más nuevo disponible.',explanation:'La novedad no demuestra que el diseño cumpla requisitos ni reduzca riesgos.'},{text:'Aumentar permisos para evitar errores.',explanation:'Permisos amplios ocultan problemas y contradicen menor privilegio.'},{text:'Ejecutar un único test manual.',explanation:'Un test aislado no revisa decisiones de arquitectura ni trade-offs.'},{text:'Revisar la solución con los pilares Well-Architected.',explanation:'Correcta: el marco ordena preguntas sobre seguridad, confiabilidad, operación, rendimiento y costo.'}]},
  {id:'aws-quiz-u26-09',unitId:26,lessonId:'aws-u26-l3',prompt:'El checkout debe recuperarse de un fallo sin perder más de cinco minutos de pedidos. ¿Qué pilar orienta esa conversación?',correctIndex:0,options:[{text:'Confiabilidad, mediante RTO, RPO y recuperación probada.',explanation:'Correcta: el requisito habla de continuidad y pérdida tolerada; se diseña y prueba contra esos objetivos.'},{text:'Excelencia operativa, solamente con nombres de recursos.',explanation:'Los nombres ayudan a operar, pero no definen recuperación ni pérdida de datos.'},{text:'Sostenibilidad, reduciendo el tamaño de logs.',explanation:'Puede ser valioso, pero no responde al objetivo de recuperación del checkout.'},{text:'Estilo de código Java, usando records.',explanation:'El estilo mejora mantenibilidad, pero no establece una estrategia de continuidad.'}]},
  {id:'aws-quiz-u26-10',unitId:26,lessonId:'aws-u26-l3',prompt:'Un ADR propone dos regiones para una carga pequeña. ¿Qué debe documentar antes de aprobarlo?',correctIndex:1,options:[{text:'Solo el nombre comercial de las regiones.',explanation:'Los nombres no justifican el costo ni la complejidad adicional de operar dos regiones.'},{text:'Riesgo cubierto, RTO/RPO, costo y alternativa más simple.',explanation:'Correcta: una decisión de arquitectura necesita trade-offs verificables, no una preferencia tecnológica.'},{text:'Que toda aplicación debe ser multi-región.',explanation:'No es una regla universal; muchas cargas se resuelven correctamente con una región y Multi-AZ.'},{text:'Una política IAM con acceso total.',explanation:'El acceso total no justifica aislamiento geográfico y agrega exposición de seguridad.'}]},
];

// U26 conserva su versión revisada; U27–U37 usan bancos redactados con casos y explicaciones específicas.
export const awsQuizzes: QuizQuestion[] = [
  ...originalAwsQuizzes.filter(question => question.unitId === 26),
  ...awsQuizzesU27U31,
  ...awsQuizzesU32U37,
  ...awsQuizzesU38,
  ...awsGuideQuizAdditions,
];
