import type { Lab, GlossaryEntry } from '../../types';

export const awsGlossary: readonly GlossaryEntry[] = [
 ['Computación en la nube','Uso bajo demanda de recursos de cómputo, almacenamiento y otros servicios a través de internet o APIs, con capacidad de aprovisionarlos y pagar según el modelo de uso.','Fundamentos'],
 ['Amazon Web Services (AWS)','Plataforma de nube de Amazon que ofrece servicios de infraestructura y servicios administrados en regiones geográficas.','Fundamentos'],
 ['IaaS / PaaS / SaaS','Modelos que describen cuánto administra el proveedor: infraestructura, plataforma de ejecución o aplicación terminada. Las responsabilidades concretas dependen del servicio.','Fundamentos'],
 ['Región AWS','Área geográfica que agrupa varias zonas de disponibilidad; la elección considera latencia, requisitos de datos, costo y servicios disponibles.','Infraestructura'],
 ['Availability Zone','Ubicación aislada dentro de una región; distribuir recursos entre zonas puede reducir fallos correlacionados.','Cloud'],
 ['Shared Responsibility Model','AWS protege la infraestructura de la nube y el cliente configura la seguridad de lo que ejecuta en ella; el reparto depende del servicio.','Seguridad'],
 ['Well-Architected Framework','Marco para revisar decisiones de arquitectura en excelencia operativa, seguridad, confiabilidad, eficiencia, costo y sostenibilidad.','Arquitectura'],
 ['IAM Role','Identidad con permisos asumibles por personas o servicios para obtener credenciales temporales.','IAM'],
 ['IAM principal','Entidad que realiza una solicitud autenticada a AWS, como un usuario, un rol asumido o un servicio.','IAM'],
 ['IAM policy','Documento JSON que permite o deniega acciones sobre recursos, con condiciones opcionales; una denegación explícita prevalece.','IAM'],
 ['Least privilege','Conceder solo las acciones y recursos necesarios durante el menor tiempo posible.','Seguridad'],
 ['VPC','Red virtual aislada donde se definen direcciones, subredes y reglas de conectividad.','Redes'],
 ['CIDR','Notación que representa un rango de direcciones IP, por ejemplo 10.0.0.0/16 para una red.','Redes'],
 ['Subred','Parte de un rango CIDR de una VPC asociada a una zona de disponibilidad. Sus rutas determinan cómo se conecta.','Redes'],
 ['Route table','Reglas de una VPC que eligen el siguiente destino de red para el tráfico según su rango IP.','Redes'],
 ['Internet Gateway / NAT Gateway','Internet Gateway conecta una VPC con internet cuando las rutas y reglas lo permiten; NAT permite conexiones salientes desde redes privadas.','Redes'],
 ['Security Group','Firewall con estado asociado a recursos; define tráfico permitido de entrada y salida.','Redes'],
 ['Network ACL (NACL)','Filtro de red sin estado aplicado a una subred; evalúa reglas numeradas de entrada y salida.','Redes'],
 ['Amazon EC2','Servicio de máquinas virtuales configurables; el equipo elige capacidad y administra el sistema operativo y la aplicación.','Cómputo'],
 ['Elastic Load Balancing','Distribuye conexiones o solicitudes entre destinos saludables; el tipo de balanceador determina protocolos y reglas disponibles.','Cómputo'],
 ['Auto Scaling','Ajusta la capacidad de un grupo de instancias según políticas y señales configuradas; no corrige por sí solo una aplicación con estado local.','Cómputo'],
 ['S3 bucket','Contenedor regional de Amazon S3 en el que se almacenan objetos y se configuran controles de acceso y ciclo de vida.','Almacenamiento'],
 ['S3 object','Unidad almacenada en S3 compuesta por datos, una clave y metadatos; puede tener versiones si el bucket tiene versionado.','Almacenamiento'],
 ['S3 key','Nombre que identifica un objeto dentro de un bucket. Los separadores como / son parte del nombre y no directorios reales.','Almacenamiento'],
 ['S3 presigned URL','URL temporal que concede acceso a una operación concreta de un objeto sin compartir credenciales.','Almacenamiento'],
 ['RDS','Servicio administrado para bases relacionales; AWS opera parte de las tareas de infraestructura y mantenimiento.','Datos'],
 ['DynamoDB partition key','Atributo que determina la partición lógica y afecta distribución y patrones de consulta.','Datos'],
 ['SQS visibility timeout','Intervalo durante el cual un mensaje recibido permanece oculto a otros consumidores antes de borrarse o volver a estar disponible.','Mensajería'],
 ['Dead-letter queue','Cola de aislamiento para mensajes que exceden la política de reintentos configurada.','Mensajería'],
 ['EventBridge','Servicio para enrutar eventos entre productores, reglas y destinos desacoplados.','Mensajería'],
 ['SNS fan-out','Patrón donde un tópico SNS entrega una notificación a varias suscripciones; cada consumidor puede procesarla de forma independiente.','Mensajería'],
 ['CloudWatch','Servicio de AWS para métricas, logs, alarmas y señales operativas.','Operación'],
 ['CloudWatch dimension','Par de nombre y valor que identifica una serie de métricas; usar valores únicos ilimitados puede disparar cardinalidad y costo.','Operación'],
 ['CloudTrail','Registro de actividad de API y acciones en una cuenta AWS, útil para auditoría e investigación.','Operación'],
 ['AWS SDK for Java 2.x','Biblioteca Java para invocar servicios AWS mediante clientes tipados y proveedores de credenciales.','Java en AWS'],
 ['Credential provider chain','Orden de fuentes que el SDK consulta para descubrir credenciales; en AWS se prefieren credenciales temporales del rol.','Java en AWS'],
 ['Endpoint override','Configuración que dirige un cliente SDK a un endpoint alternativo durante pruebas; en producción apunta al servicio AWS de la región elegida.','Java en AWS'],
 ['Lambda handler','Método de entrada que recibe un evento y contexto de ejecución para procesar una invocación.','Serverless'],
 ['Lambda event source mapping','Configuración que lee eventos de una fuente como SQS y los entrega por lotes a una función Lambda.','Serverless'],
 ['Cold start','Tiempo adicional de inicialización que puede aparecer al crear un entorno nuevo de ejecución serverless.','Serverless'],
 ['ECR','Registro de imágenes de contenedor integrado con servicios de AWS.','Contenedores'],
 ['ECS task definition','Plantilla que especifica imagen, recursos, puertos, variables y roles para ejecutar contenedores en ECS.','Contenedores'],
 ['ECS service','Controlador que mantiene la cantidad deseada de tareas y puede integrarse con balanceo y despliegues progresivos.','Contenedores'],
 ['ECS Fargate','Ejecución de tareas y servicios de contenedores sin administrar directamente servidores EC2.','Contenedores'],
 ['RTO / RPO','Objetivo de tiempo para recuperar un servicio y objetivo de pérdida máxima de datos tras una interrupción.','Resiliencia'],
 ['AWS SAM','Framework y CLI para definir, construir y probar aplicaciones serverless de AWS.','Despliegue'],
 ['Floci','Emulador local compatible con operaciones de servicios AWS. Su cobertura depende de la versión y operación; no equivale a validar AWS real.','Laboratorio'],
 ['Idempotencia','Propiedad por la que repetir una operación con la misma identidad no crea un efecto de negocio duplicado.','Mensajería'],
 ['Fallo parcial de lote','Respuesta que identifica elementos fallidos en un lote para permitir su reintento sin repetir innecesariamente los elementos exitosos.','Serverless'],
];

export const awsLabs: readonly Lab[] = [
 {title:'Proyecto AWS con Floci: pedidos de punta a punta',repository:'https://github.com/JonasGarcia1/aws-java-floci-labs',description:'Laboratorio Java 21 para recorrer una API Spring Boot, S3, SQS, Lambda y DynamoDB en un entorno local. La unidad 37 prepara la arquitectura; esta unidad guía la ejecución.',requirements:'Java 21, Maven, Docker y AWS CLI v2. Usá solo el perfil local floci y las credenciales ficticias test/test.',steps:['Prepará el perfil local e iniciá Floci desde la primera lección.','Creá bucket, colas y tabla con los scripts de preparación del laboratorio.','Levantá Spring Boot, publicá un pedido y seguí el objeto y el mensaje.','Configurá y ejecutá la función Java 21 con el mapeo SQS, verificando escritura idempotente y DLQ.','Ejecutá las pruebas del proyecto y compará la evidencia local con los límites indicados.','Detené los contenedores locales al terminar.'],links:[{title:'Floci: servicios compatibles',url:'https://floci.io/floci/services/'},{title:'Floci: servicio Lambda',url:'https://floci.io/floci/services/lambda/'},{title:'AWS Lambda con SQS: manejo de errores',url:'https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html'}],lessonId:'aws-u38-l1'},
];
