// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import { ProgressProvider } from '../lib/progress';
import { STORAGE_KEY } from '../lib/study';
import { LessonPage } from './Lesson';
import { QuestionsPage } from './Questions';
import { PracticePage } from './Practice';
import { ProgressPage } from './Progress';
import { Roadmap } from './Roadmap';
import { ResourcesPage } from './Resources';
import { lessons, questions, units } from '../content';
function wrap(node:React.ReactNode, path='/'){return render(<MemoryRouter initialEntries={[path]}><ProgressProvider>{node}</ProgressProvider></MemoryRouter>);}
beforeEach(()=>{localStorage.clear();vi.spyOn(window,'scrollTo').mockImplementation(()=>{});});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
describe('recorrido de estudio',()=>{
 it('accede directamente a una lección, conserva pendiente al leer y persiste el estado manual',async()=>{wrap(<Routes><Route path="/leccion/:id" element={<LessonPage/>}/></Routes>,'/leccion/u03-c');expect(await screen.findByRole('heading',{name:lessons.find(l=>l.id==='u03-c')!.title,level:1})).toBeInTheDocument();await screen.findByRole('heading',{name:'Concepto',level:2});expect(screen.getByLabelText('Estado de esta lección')).toHaveValue('pendiente');fireEvent.change(screen.getByLabelText('Estado de esta lección'),{target:{value:'repasado'}});await waitFor(()=>expect(JSON.parse(localStorage.getItem(STORAGE_KEY)!).statuses['u03-c']).toBe('repasado'));});
 it('busca preguntas y filtra favoritos después de guardarlos',()=>{const q=questions[0];wrap(<QuestionsPage/>);fireEvent.change(screen.getByLabelText('Buscar preguntas'),{target:{value:q.prompt}});expect(screen.getByRole('heading',{name:q.prompt})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Guardar en favoritos'}));fireEvent.click(screen.getByRole('button',{name:'Favoritos'}));expect(screen.getByRole('heading',{name:q.prompt})).toBeInTheDocument();expect(screen.getByText('Ver respuesta y razonamiento').closest('details')).not.toHaveAttribute('open');});
 it('permite abrir cada unidad desde su cabecera hacia la primera lección',()=>{const unit=units.find(item=>item.id===15)!;const first=lessons.find(item=>item.unitId===unit.id)!;wrap(<Roadmap/>);expect(screen.getByRole('link',{name:`Abrir ${unit.title}: ${first.title}`})).toHaveAttribute('href',`/leccion/${first.id}`);});
 it('abre los cuatro cheat sheets PDF desde Recursos',()=>{wrap(<ResourcesPage/>);fireEvent.click(screen.getByRole('button',{name:'Cheat sheets'}));const links=screen.getAllByRole('link',{name:'Abrir cheat sheet'});expect(links).toHaveLength(4);for(const link of links){expect(link).toHaveAttribute('href',expect.stringMatching(/\.pdf$/));expect(link).toHaveAttribute('target','_blank');}});
 it('incluye las unidades nuevas en preguntas y práctica',()=>{wrap(<QuestionsPage/>);fireEvent.change(screen.getByLabelText('Filtrar preguntas por unidad'),{target:{value:'25'}});expect(screen.getByText('6 preguntas encontradas')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'¿Qué aporta un Schema Registry?'})).toBeInTheDocument();cleanup();wrap(<PracticePage/>);fireEvent.change(screen.getByLabelText('¿Qué querés practicar?'),{target:{value:'25'}});expect(screen.getByText('10 preguntas sin repetir')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/Empezar quiz/}));expect(screen.getByText('Contratos y operación de eventos')).toBeInTheDocument();});
 it('lleva los laboratorios a sus repositorios públicos de GitHub',()=>{wrap(<ResourcesPage/>);fireEvent.click(screen.getByRole('button',{name:'Laboratorios'}));const links=screen.getAllByRole('link',{name:'Abrir repositorio en GitHub'});expect(links).toHaveLength(3);expect(links.map(link=>link.getAttribute('href'))).toEqual(['https://github.com/JonasGarcia1/springboot-kafka-roadmap-course','https://github.com/JonasGarcia1/springboot-kafka-roadmap-course/tree/main/advanced-labs','https://github.com/JonasGarcia1/springboot-kafka-order-events-lab']);for(const link of links)expect(link).toHaveAttribute('target','_blank');expect(screen.queryByText('Carpeta dentro de repaso-roadmap')).not.toBeInTheDocument();});
 it('el quiz exige elegir, explica todas las opciones y guarda la respuesta',async()=>{wrap(<PracticePage/>);fireEvent.click(screen.getByRole('button',{name:/Empezar quiz/}));expect(screen.getByRole('button',{name:'Comprobar respuesta'})).toBeDisabled();fireEvent.click(screen.getAllByRole('radio')[0]);fireEvent.click(screen.getByRole('button',{name:'Comprobar respuesta'}));expect(document.querySelectorAll('.option-explanation')).toHaveLength(4);await waitFor(()=>expect(Object.keys(JSON.parse(localStorage.getItem(STORAGE_KEY)!).quizResults)).toHaveLength(1));expect(screen.getByRole('button',{name:/Siguiente pregunta/})).toBeInTheDocument();});
 it('simulacro revela puntos esperados y registra autoevaluación, sin puntuar texto',async()=>{wrap(<PracticePage/>,'/practica?modo=entrevista');fireEvent.click(screen.getByRole('button',{name:/Empezar simulacro/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Mi razonamiento personal'}});fireEvent.click(screen.getByRole('button',{name:'Comparar con una respuesta orientativa'}));expect(screen.getByRole('heading',{name:'¿Mencionaste estos puntos?'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Necesito repasarla'}));await waitFor(()=>expect(Object.values(JSON.parse(localStorage.getItem(STORAGE_KEY)!).interviewResults)).toEqual(['repasar']));expect(localStorage.getItem(STORAGE_KEY)).not.toContain('Mi razonamiento personal');expect(screen.getByRole('textbox')).toHaveValue('');});
 it('exporta un archivo JSON con el progreso actual',()=>{const create=vi.fn(()=> 'blob:test');const revoke=vi.fn();Object.defineProperty(URL,'createObjectURL',{value:create,configurable:true});Object.defineProperty(URL,'revokeObjectURL',{value:revoke,configurable:true});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});wrap(<ProgressPage/>);fireEvent.click(screen.getByRole('button',{name:'Exportar progreso'}));expect(create).toHaveBeenCalledWith(expect.any(Blob));expect(screen.getByRole('status')).toHaveTextContent('exportada');});
 it('importa solo tras revisar la copia y conserva el resultado al volver a abrir',async()=>{const data={version:1,statuses:{'u03-c':'repasado'},favorites:['u03-c'],quizResults:{},interviewResults:{}};const file=new File([JSON.stringify(data)],'avance.json',{type:'application/json'});Object.defineProperty(file,'text',{value:async()=>JSON.stringify(data)});wrap(<ProgressPage/>);fireEvent.change(screen.getByLabelText('Archivo de progreso'),{target:{files:[file]}});await screen.findByRole('heading',{name:'Resumen de la copia'});expect(localStorage.getItem(STORAGE_KEY)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Reemplazar con esta copia'}));await waitFor(()=>expect(JSON.parse(localStorage.getItem(STORAGE_KEY)!).statuses['u03-c']).toBe('repasado'));cleanup();wrap(<Routes><Route path="/leccion/:id" element={<LessonPage/>}/></Routes>,'/leccion/u03-c');expect(screen.getByLabelText('Estado de esta lección')).toHaveValue('repasado');});
 it('no sobrescribe datos corruptos simplemente por abrir una lección',async()=>{localStorage.setItem(STORAGE_KEY,'{dato dañado');wrap(<Routes><Route path="/leccion/:id" element={<LessonPage/>}/></Routes>,'/leccion/u03-c');await screen.findByRole('heading',{name:'Concepto',level:2});expect(localStorage.getItem(STORAGE_KEY)).toBe('{dato dañado');});
});

