import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BookOpen, CheckCheck, Clock3, Compass, MessageCircle, Sparkles, Target, Zap } from 'lucide-react';
import { lessons, units, stages, questions, quizzes } from '../content';
import { useProgress } from '../lib/progress';
import { PageHeading, ProgressBar, LessonRow } from '../components/ui';
export function Home() {
 const {progress}=useProgress();const done=lessons.filter(l=>progress.statuses[l.id]==='repasado');
 const current=lessons.find(l=>l.id===progress.lastLesson)||lessons.find(l=>progress.statuses[l.id]!=='repasado')||lessons[0];
 const review=lessons.filter(l=>progress.statuses[l.id]==='reforzar');
 const favorites=lessons.filter(l=>progress.favorites.includes(l.id));
 const quizAnswered=quizzes.filter(q=>progress.quizResults[q.id]!==undefined).length;
 return <><PageHeading eyebrow="UN POCO CADA DÍA, UN POCO MÁS LEJOS" title="Espacio de repaso" description="Conectar lo que sabemos. Practicar lo que falta. Llegar con confianza." action={<span className="pill"><span className="green-dot"/>Backend Java · {stages.length} etapas</span>}/>
 <div className="dashboard-top"><section className="continue-card"><div className="continue-content"><span className="eyebrow light"><span className="small-line"/>{progress.lastLesson?'RETOMÁ DONDE QUEDASTE':'TU PRÓXIMO PASO'}</span><span className="continue-unit">UNIDAD {String(current.unitId).padStart(2,'0')} · {units.find(u=>u.id===current.unitId)?.title}</span><h2>{current.title}</h2><p>{current.description}</p><div className="continue-actions"><Link className="button lime" to={`/leccion/${current.id}`}>{progress.lastLesson?'Continuar lección':'Empezar a aprender'}<ArrowRight size={17}/></Link><span><Clock3 size={14}/>{current.minutes} min de lectura</span></div></div><div className="learning-map" aria-hidden="true"><div className="map-orbit one"/><div className="map-orbit two"/><span className="map-node node-java">{'{ }'}<small>JAVA</small></span><span className="map-node node-spring"><span>↗</span><small>SPRING</small></span><span className="map-node node-end"><CheckCheck size={24}/></span><span className="map-caption">Una idea.<br/>Una conexión más.</span></div></section>
 <Link to="/practica?modo=entrevista" className="interview-promo"><span className="promo-icon"><MessageCircle size={24}/></span><span className="eyebrow">PASÁ DE SABER A EXPLICAR</span><h2>¿Y si la entrevista<br/> fuera hoy?</h2><p>10 preguntas para ordenar tus ideas y responder con tus palabras.</p><strong>Iniciar simulacro <ArrowUpRight size={18}/></strong></Link></div>
 <div className="stat-grid"><div><span className="stat-icon green"><BookOpen size={20}/></span><div><strong>{lessons.length}<small>lecciones</small></strong><span>Breves y claras</span></div></div><div><span className="stat-icon blue"><MessageCircle size={20}/></span><div><strong>{questions.length}<small>preguntas</small></strong><span>De entrevistas y casos prácticos</span></div></div><div><span className="stat-icon amber"><CheckCheck size={20}/></span><div><strong>{done.length}<small>repasadas</small></strong><span>Avance, debe ser marcado</span></div></div><div><span className="stat-icon purple"><Target size={20}/></span><div><strong>{quizAnswered}<small>respondidas</small></strong><span>De {quizzes.length} preguntas de quiz</span></div></div></div>
 <section className="roadmap-overview"><div className="section-heading"><div><span className="eyebrow">UN RECORRIDO, PASO A PASO</span><h2>Roadmap de Java</h2></div><Link className="text-link" to="/roadmap">Ver recorrido completo <ArrowRight size={16}/></Link></div><div className="stage-grid">{stages.map((stage,index)=>{const stageUnits=units.filter(u=>u.level===stage.name);const ids=new Set(stageUnits.map(u=>u.id));const stageLessons=lessons.filter(l=>ids.has(l.unitId));const completed=stageLessons.filter(l=>progress.statuses[l.id]==='repasado').length;return <Link className={`stage-card stage-${index} stage-${stage.color}`} to={`/roadmap?etapa=${index}`} key={stage.id}><div className="stage-card-top"><span className="stage-number">{String(index+1).padStart(2,'0')}</span><ArrowUpRight size={19}/></div><h3>{stage.name}</h3><p>{stage.description}</p><span className="stage-topics">{stage.topics}</span><div className="stage-card-bottom"><ProgressBar value={completed} total={stageLessons.length}/><div><span>{stageUnits.length} unidades</span><span>{completed}/{stageLessons.length} repasadas</span></div></div></Link>;})}</div></section>
 <div className="home-lower"><section className="panel"><div className="section-heading"><h2>{review.length?'Para volver a practicar':favorites.length?'Lecciones guardadas':'Empezar por las bases'}</h2><span className="subtle-icon"><Compass size={20}/></span></div>{(review.length?review:favorites.length?favorites:lessons).slice(0,3).map((lesson,index)=><LessonRow key={lesson.id} lesson={lesson} index={index}/>)}</section><section className="study-tip"><Sparkles size={22}/><span className="eyebrow">UNA FORMA DE ESTUDIAR</span><h2>Entender es poder<br/>explicarlo simple.</h2><p>Leé un concepto, cerrá la respuesta y contalo en voz alta. Después, probalo con un ejemplo.</p><Link to="/preguntas">Practicar una respuesta <Zap size={16}/></Link></section></div></>;
}
