import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, Clock3, MessageCircle } from 'lucide-react';
import { lessons, units, levels, questions, loadLesson } from '../content';
import { Favorite, LessonBody, ExternalLink } from '../components/ui';
import { useProgress } from '../lib/progress';
import { statusLabels, splitSections } from '../lib/study';
import type { StudyStatus } from '../types';
export function LessonPage() {const {id}=useParams();const lesson=lessons.find(l=>l.id===id);if(!lesson)return <div className="empty-state"><h1>Lección no encontrada</h1><Link to="/roadmap">Volver al roadmap</Link></div>;return <LessonView key={lesson.id} id={lesson.id}/>;}
function LessonView({id}:{id:string}) {
 const lesson=lessons.find(l=>l.id===id)!;const unit=units.find(u=>u.id===lesson.unitId)!;const {progress,update,warning}=useProgress();const [text,setText]=useState('');const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 const index=lessons.findIndex(l=>l.id===id);const previous=lessons[index-1];const next=lessons[index+1];const related=questions.filter(q=>q.lessonId===id).slice(0,3);
 useEffect(()=>{let cancelled=false;setError('');loadLesson(id).then(t=>{if(!cancelled)setText(t);}).catch(()=>{if(!cancelled)setError('No pudimos cargar esta lección. Volvé a intentarlo.');});return()=>{cancelled=true;};},[id,retry]);
 useEffect(()=>{if(!warning)update(p=>p.lastLesson===id?p:{...p,lastLesson:id});document.title=`${lesson.title} · Repaso`;},[id]);
 return <><Link className="back-link" to={`/roadmap?etapa=${levels.indexOf(unit.level)}`}><ArrowLeft size={16}/>Volver al roadmap</Link><header className="lesson-header"><div className="eyebrow">UNIDAD {String(unit.id).padStart(2,'0')} · {unit.level}</div><div className="lesson-title"><h1>{lesson.title}</h1><Favorite id={id}/></div><p>{lesson.description}</p><div className="lesson-meta"><span><Clock3 size={15}/>{lesson.minutes} min + práctica</span><span>Java 21 · versiones señaladas en el contenido</span></div></header>
 <div className="lesson-layout"><article className="lesson-article"><section className="learning-objectives"><span className="eyebrow">AL TERMINAR VAS A PODER</span><ul>{lesson.objectives.map(o=><li key={o}><Check size={16}/>{o}</li>)}</ul><p><strong>Antes de empezar:</strong> {lesson.prerequisites.length?lesson.prerequisites.map((p,i)=>{const prerequisite=lessons.find(l=>l.id===p);return <span key={p}>{i>0?' · ':''}{prerequisite?<Link to={`/leccion/${p}`}>{prerequisite.title}</Link>:p}</span>}):'No necesitás conocimientos previos.'}</p></section>{error?<div role="alert" className="notice warning">{error} <button onClick={()=>setRetry(n=>n+1)}>Reintentar</button></div>:!text?<p role="status">Preparando tu lección…</p>:<LessonBody text={text}/>}
 <section className="lesson-sources"><h2>Para seguir explorando</h2>{lesson.resources.map(r=><ExternalLink key={r.url} href={r.url}>{r.title}</ExternalLink>)}</section>
 <div className="lesson-finish"><div><h2>¿Cómo te sentís con este tema?</h2><p>Marcá tu estado. Leer la página no la completa automáticamente.</p></div><select aria-label="Estado de esta lección" value={progress.statuses[id]||'pendiente'} onChange={e=>update(p=>({...p,statuses:{...p.statuses,[id]:e.target.value as StudyStatus}}))}>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><nav className="lesson-pagination" aria-label="Lecciones anterior y siguiente">{previous?<Link to={`/leccion/${previous.id}`}><ArrowLeft size={18}/><span><small>ANTERIOR</small>{previous.title}</span></Link>:<span/>}{next?<Link to={`/leccion/${next.id}`}><span><small>SIGUIENTE</small>{next.title}</span><ArrowRight size={18}/></Link>:<Link to="/practica">Ponerlo en práctica<ArrowRight size={18}/></Link>}</nav></article>
 <aside className="lesson-aside"><div className="sticky-toc"><span className="eyebrow">EN ESTA LECCIÓN</span><nav aria-label="Índice de la lección">{splitSections(text).map((s,i)=><a key={i} href={`#section-${i}`}>{s.title}</a>)}</nav><div className="aside-practice"><MessageCircle size={22}/><h3>Explicalo con tus palabras</h3><p>La respuesta es un punto de partida. Tu razonamiento hace la diferencia.</p><Link to={`/preguntas?unidad=${unit.id}`}>Preguntas de esta unidad <ArrowRight size={15}/></Link></div>{related.length>0&&<div className="aside-related"><span className="eyebrow">TE PUEDEN PREGUNTAR</span>{related.map(q=><Link key={q.id} to={`/preguntas?q=${encodeURIComponent(q.prompt)}`}>{q.prompt}</Link>)}</div>}</div></aside></div></>;
}
