import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, CheckCircle2, MessageCircle, RotateCcw, Target, Zap } from 'lucide-react';
import { getModule } from '../content/catalog';
import type { ModuleId } from '../types';
import { modulePath } from '../components/module';
import { PageHeading, ProgressBar, Prose, EmptyState } from '../components/ui';
import { sampleUnique } from '../lib/study';
import { useProgress } from '../lib/progress';
import type { Question, QuizQuestion } from '../types';
export function PracticePage({moduleId='java'}:{moduleId?:ModuleId}) {
 const {questions,quizzes,units,title}=getModule(moduleId);const path=(to:string)=>modulePath(moduleId,to);
 const [params,setParams]=useSearchParams();const mode=params.get('modo')==='entrevista'?'entrevista':'quiz';const [unit,setUnit]=useState('');const [session,setSession]=useState<{mode:string;items:(Question|QuizQuestion)[]}|null>(null);
 function start(){const pool=mode==='quiz'?quizzes:questions;const filtered=pool.filter(q=>!unit||q.unitId===Number(unit));setSession({mode,items:sampleUnique<Question|QuizQuestion>(filtered,10)});}
 return <><PageHeading eyebrow="EL CONOCIMIENTO SE ENTRENA" title={`Tu zona de práctica · ${title}`} description="Equivocarte acá también es avanzar. Mirá el razonamiento y volvé a intentarlo."/>{session?<>{session.mode==='quiz'?<QuizSession key={session.items.map(q=>q.id).join()} items={session.items as QuizQuestion[]} onExit={()=>setSession(null)} moduleId={moduleId}/>:<InterviewSession key={session.items.map(q=>q.id).join()} items={session.items as Question[]} onExit={()=>setSession(null)} moduleId={moduleId}/>}</>:<><div className="practice-modes" role="group" aria-label="Modo de práctica"><button className={mode==='quiz'?'mode-card active':'mode-card'} onClick={()=>setParams({})}><span className="mode-icon"><Zap size={25}/></span><div><h2>Quiz de conceptos</h2><p>Elegí una respuesta y entendé por qué cada opción es correcta o incorrecta.</p></div><span className="selection-circle"/></button><button className={mode==='entrevista'?'mode-card active':'mode-card'} onClick={()=>setParams({modo:'entrevista'})}><span className="mode-icon"><MessageCircle size={25}/></span><div><h2>Simulacro de entrevista</h2><p>Respondé con tus palabras y compará tu explicación con los puntos esperados.</p></div><span className="selection-circle"/></button></div><section className="practice-setup panel"><span className="eyebrow">PREPARÁ TU SESIÓN</span><h2>{mode==='quiz'?'Una pregunta, una idea más clara.':'Tu propia forma de responder.'}</h2><label className="field-label">¿Qué querés practicar?<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Todo el roadmap · mezcla de niveles</option>{units.map(u=><option key={u.id} value={u.id}>{u.id}. {u.title}</option>)}</select></label><div className="practice-summary"><span><Target size={18}/>{Math.min(10,(mode==='quiz'?quizzes:questions).filter(q=>!unit||q.unitId===Number(unit)).length)} preguntas sin repetir</span><span><CheckCircle2 size={18}/>{mode==='quiz'?'Explicación por opción':'Autoevaluación, sin calificación automática'}</span></div><button className="button primary" onClick={start}>Empezar {mode==='quiz'?'quiz':'simulacro'}<ArrowRight size={17}/></button></section><div className="notice">El resultado de una práctica no cambia el estado de tus lecciones. Vos decidís qué tema está repasado y cuál necesita otra vuelta.</div></>}</>;
}
function QuizSession({items,onExit,moduleId}:{items:QuizQuestion[];onExit:()=>void;moduleId:ModuleId}) {const path=(to:string)=>modulePath(moduleId,to);const {units}=getModule(moduleId);
 const [index,setIndex]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [checked,setChecked]=useState(false);const [answers,setAnswers]=useState<Record<string,number>>({});const {update}=useProgress();
 const done=index>=items.length;const q=items[index];const score=items.filter(q=>answers[q.id]===q.correctIndex).length;
 if(!items.length)return <EmptyState title="No hay preguntas disponibles"><button onClick={onExit}>Elegir otra unidad</button></EmptyState>;
 if(done)return <section className="session-result panel"><span className="result-icon"><CheckCircle2 size={36}/></span><span className="eyebrow">SESIÓN TERMINADA</span><h2>{score} de {items.length} respuestas correctas</h2><p>El valor está en lo que te llevás de cada explicación.</p><div className="result-list">{items.map(q=><div key={q.id}><span className={answers[q.id]===q.correctIndex?'result-good':'result-review'}>{answers[q.id]===q.correctIndex?'Correcta':'Para repasar'}</span><Link to={path(`/leccion/${q.lessonId}`)}>{q.prompt}<ArrowRight size={15}/></Link></div>)}</div><button className="button primary" onClick={onExit}><RotateCcw size={16}/>Preparar otra sesión</button></section>;
 function verify(){if(choice===null)return;setAnswers(a=>({...a,[q.id]:choice}));setChecked(true);update(p=>({...p,quizResults:{...p.quizResults,[q.id]:choice}}));}
 return <section className="session panel"><div className="session-top"><span className="eyebrow">QUIZ · {index+1} DE {items.length}</span><button className="text-button" onClick={onExit}>Salir de la sesión</button></div><ProgressBar value={index} total={items.length} label="Preguntas respondidas"/><span className="tag">{units.find(u=>u.id===q.unitId)?.title}</span><h2>{q.prompt}</h2><fieldset className="quiz-options"><legend className="sr-only">Elegí una respuesta</legend>{q.options.map((o,i)=><label className={`quiz-option ${choice===i?'selected':''} ${checked?(i===q.correctIndex?'correct':choice===i?'incorrect':''):''}`} key={i}><input type="radio" name={q.id} checked={choice===i} disabled={checked} onChange={()=>setChoice(i)}/><span className="option-letter">{String.fromCharCode(65+i)}</span><span><strong>{o.text}</strong>{checked&&<span className="option-explanation">{i===q.correctIndex?'Correcta. ':choice===i?'Tu respuesta. ':''}{o.explanation}</span>}</span></label>)}</fieldset>{checked?<div className="session-bottom"><p role="status">{choice===q.correctIndex?'¡Bien! Ese es el razonamiento.':'Una oportunidad para aclarar el concepto.'} <Link to={path(`/leccion/${q.lessonId}`)}>Ver lección</Link></p><button className="button primary" onClick={()=>{setIndex(i=>i+1);setChoice(null);setChecked(false);}}>{index===items.length-1?'Ver resultado':'Siguiente pregunta'}<ArrowRight size={16}/></button></div>:<button className="button primary" disabled={choice===null} onClick={verify}>Comprobar respuesta</button>}</section>;
}
function InterviewSession({items,onExit,moduleId}:{items:Question[];onExit:()=>void;moduleId:ModuleId}) {const path=(to:string)=>modulePath(moduleId,to);
 const [index,setIndex]=useState(0);const [draft,setDraft]=useState('');const [revealed,setRevealed]=useState(false);const [grades,setGrades]=useState<Record<string,'repasar'|'bien'>>({});const {update}=useProgress();const q=items[index];
 if(index>=items.length)return <section className="session-result panel"><span className="result-icon"><MessageCircle size={32}/></span><span className="eyebrow">SIMULACRO TERMINADO</span><h2>Ya pusiste tus ideas en palabras.</h2><p>Según tu autoevaluación: {Object.values(grades).filter(g=>g==='bien').length} respuestas claras y {Object.values(grades).filter(g=>g==='repasar').length} para reforzar. Esto no es una evaluación automática.</p><div className="result-list">{items.map(item=><div key={item.id}><span className={grades[item.id]==='bien'?'result-good':'result-review'}>{grades[item.id]==='bien'?'Me salió bien':'Voy a repasarla'}</span><Link to={path(`/leccion/${item.lessonId}`)}>{item.prompt}<ArrowRight size={15}/></Link></div>)}</div><button className="button primary" onClick={onExit}><RotateCcw size={16}/>Preparar otro simulacro</button></section>;
 function grade(value:'repasar'|'bien'){setGrades(g=>({...g,[q.id]:value}));update(p=>({...p,interviewResults:{...p.interviewResults,[q.id]:value}}));setIndex(i=>i+1);setDraft('');setRevealed(false);}
 return <section className="session panel"><div className="session-top"><span className="eyebrow">SIMULACRO · {index+1} DE {items.length}</span><button className="text-button" onClick={onExit}>Salir de la sesión</button></div><ProgressBar value={index} total={items.length}/><span className="tag">{q.level}</span><h2>{q.prompt}</h2><label className="field-label">Tu respuesta (opcional: también podés decirla en voz alta)<textarea rows={5} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Empezá por la idea central, sumá un ejemplo y explicá sus límites…"/></label><p className="footnote">Este borrador dura solo esta pregunta. Se guarda tu autoevaluación, no el texto.</p>{!revealed?<button className="button primary" onClick={()=>setRevealed(true)}>Comparar con una respuesta orientativa</button>:<div className="interview-feedback"><span className="eyebrow">UNA RESPUESTA POSIBLE</span><Prose text={q.shortAnswer}/><details className="reveal"><summary>Ampliar explicación</summary><Prose text={q.answer}/></details><h3>¿Mencionaste estos puntos?</h3><ul>{q.keyPoints.map(k=><li key={k}>{k}</li>)}</ul><div className="self-grade"><button className="button secondary" onClick={()=>grade('repasar')}>Necesito repasarla</button><button className="button primary" onClick={()=>grade('bien')}>Pude explicarlo <ArrowRight size={16}/></button></div></div>}</section>;
}


