import { useRef, useState, type ChangeEvent } from 'react';
import { Download, Upload, Bookmark, CheckCheck } from 'lucide-react';
import { PageHeading, LessonRow, EmptyState } from '../components/ui';
import { QuestionCard } from './Questions';
import { useProgress } from '../lib/progress';
import { parseProgress } from '../lib/study';
import { modules } from '../content/catalog';
import { Link } from 'react-router-dom';
import { ProgressBar } from '../components/ui';
import type { Progress } from '../types';
export function ProgressPage() {
 const {progress,update}=useProgress();const [message,setMessage]=useState('');const [pending,setPending]=useState<Progress|null>(null);const input=useRef<HTMLInputElement>(null);const lessons=modules.flatMap(m=>m.lessons);const questions=modules.flatMap(m=>m.questions);const quizzes=modules.flatMap(m=>m.quizzes);
 const favoriteLessons=lessons.filter(l=>progress.favorites.includes(l.id));const favoriteQuestions=questions.filter(q=>progress.favorites.includes(q.id));
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(progress,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`repaso-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Copia de progreso exportada. Guardala para recuperarla en otro navegador.');}
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';setPending(null);if(!file)return;try{if(file.size>2_000_000)throw new Error('El archivo supera los 2 MB.');const parsed=parseProgress(await file.text());const ids=new Set(lessons.map(l=>l.id));const qids=new Set(questions.map(q=>q.id));const allIds=new Set([...ids,...qids]);const quizIds=new Set(quizzes.map(q=>q.id));const removed=Object.keys(parsed.statuses).filter(id=>!ids.has(id)).length;const clean:Progress={...parsed,statuses:Object.fromEntries(Object.entries(parsed.statuses).filter(([id])=>ids.has(id))),favorites:parsed.favorites.filter(id=>allIds.has(id)),lastLesson:parsed.lastLesson&&ids.has(parsed.lastLesson)?parsed.lastLesson:undefined,quizResults:Object.fromEntries(Object.entries(parsed.quizResults).filter(([id,index])=>quizIds.has(id)&&index<quizzes.find(q=>q.id===id)!.options.length)),interviewResults:Object.fromEntries(Object.entries(parsed.interviewResults).filter(([id])=>qids.has(id)))};setPending(clean);setMessage(`Archivo válido.${removed?' Se omitieron lecciones que no existen en esta versión.':''} Revisá el resumen antes de reemplazar tu progreso.`);}catch(error){setMessage(error instanceof Error?error.message:'No pudimos leer ese archivo.');}}
 return <><PageHeading eyebrow="TU APRENDIZAJE, A TU RITMO" title="Progreso y favoritos" description="Todo se guarda en este navegador. Exportá una copia para cambiar de equipo o conservar tu avance."/><div className="stage-grid">{modules.map(m=>{const completed=m.lessons.filter(l=>progress.statuses[l.id]==='repasado').length;return <section className="stage-card panel" key={m.id}><span className="eyebrow">{m.title}</span><h2>{completed} de {m.lessons.length} lecciones repasadas</h2><ProgressBar value={completed} total={m.lessons.length}/><p>{Object.keys(progress.quizResults).filter(id=>m.quizzes.some(q=>q.id===id)).length} de {m.quizzes.length} preguntas de quiz respondidas</p><Link className="text-link" to={m.id==='aws'?'/aws':'/roadmap'}>Abrir módulo</Link></section>})}</div><div className="backup-grid"><section className="panel"><Download size={24}/><h2>Guardá una copia</h2><p>Incluye estados de las lecciones, favoritos, respuestas de quizzes y autoevaluaciones.</p><button className="button primary" onClick={download}><Download size={16}/>Exportar progreso</button></section><section className="panel"><Upload size={24}/><h2>Recuperá tu avance</h2><p>Elegí una copia JSON exportada desde Repaso. Podrás revisar el resumen antes de aplicarla.</p><input className="sr-only" type="file" accept=".json,application/json" ref={input} onChange={importFile} aria-label="Archivo de progreso"/><button className="button secondary" onClick={()=>input.current?.click()}><Upload size={16}/>Seleccionar copia</button></section></div>{message&&<div className="notice" role="status">{message}</div>}{pending&&<div className="import-preview panel"><h2>Resumen de la copia</h2><p>{Object.values(pending.statuses).filter(s=>s==='repasado').length} lecciones repasadas · {pending.favorites.length} favoritos · {Object.keys(pending.quizResults).length} respuestas de quiz.</p><p>Al importar se reemplaza el progreso actual. Podés exportarlo primero.</p><div className="button-row"><button className="button primary" onClick={()=>{update(()=>pending);setPending(null);setMessage('Tu progreso fue importado.');}}><CheckCheck size={16}/>Reemplazar con esta copia</button><button className="button secondary" onClick={()=>setPending(null)}>Cancelar</button></div></div>}<div className="section-heading"><h2><Bookmark size={22}/> Tus favoritos</h2><span>{favoriteLessons.length+favoriteQuestions.length} guardados</span></div>{favoriteLessons.length>0&&<div className="panel">{favoriteLessons.map(l=><LessonRow lesson={l} key={l.id}/>)}</div>}<div className="question-grid">{favoriteQuestions.map(q=><QuestionCard question={q} key={q.id}/>)}</div>{!favoriteLessons.length&&!favoriteQuestions.length&&<EmptyState title="Tu colección empieza con una idea">Usá el marcador de las lecciones y preguntas que quieras volver a consultar.</EmptyState>}</>;
}


