import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, Bookmark, Search } from 'lucide-react';
import { questions, units, levels } from '../content';
import type { Question } from '../types';
import { PageHeading, Favorite, Prose, EmptyState } from '../components/ui';
import { filterQuestions } from '../lib/study';
import { useProgress } from '../lib/progress';
export function QuestionCard({question:q}:{question:Question}) {return <article className="question-card"><div className="question-top"><span className="tag">{units.find(u=>u.id===q.unitId)?.title}</span><Favorite id={q.id}/></div><h2>{q.prompt}</h2><div className="question-meta"><span>{q.level}</span></div><details className="answer-reveal"><summary>Ver respuesta y razonamiento</summary><div className="short-answer"><span className="eyebrow">RESPUESTA BREVE</span><Prose text={q.shortAnswer}/></div><Prose text={q.answer}/><h3>Puntos que conviene mencionar</h3><ul>{q.keyPoints.map(k=><li key={k}>{k}</li>)}</ul><Link className="text-link" to={`/leccion/${q.lessonId}`}>Repasar la lección <ArrowRight size={15}/></Link></details></article>;}
export function QuestionsPage() {
 const [params,setParams]=useSearchParams();const query=params.get('q')||'';const unit=params.get('unidad')||'';const level=params.get('nivel')||'';const onlyFavorites=params.get('favoritos')==='1';const {progress}=useProgress();const [limit,setLimit]=useState(15);
 function change(key:string,value:string){const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);setParams(next,{replace:true});setLimit(15);}
 const filtered=filterQuestions(questions,query,unit,level,onlyFavorites?progress.favorites:undefined);
 return <><PageHeading eyebrow="ENTENDER. RECORDAR. EXPLICAR." title="Preguntas de entrevista" description="Probá responder antes de abrir la explicación y compará tu razonamiento con los puntos esperados."/><div className="question-filters"><label className="search-field"><Search size={18}/><input aria-label="Buscar preguntas" placeholder="Buscar pregunta o concepto…" value={query} onChange={e=>change('q',e.target.value)}/></label><div className="filter-selects"><select aria-label="Filtrar preguntas por unidad" value={unit} onChange={e=>change('unidad',e.target.value)}><option value="">Todas las unidades</option>{units.map(u=><option value={u.id} key={u.id}>{u.id}. {u.title}</option>)}</select><select aria-label="Filtrar preguntas por nivel" value={level} onChange={e=>change('nivel',e.target.value)}><option value="">Todos los niveles</option>{levels.map(l=><option key={l}>{l}</option>)}</select><button className={`button ${onlyFavorites?'primary':'secondary'}`} aria-pressed={onlyFavorites} onClick={()=>change('favoritos',onlyFavorites?'':'1')}><Bookmark size={16}/>Favoritos</button></div></div><div className="results-line"><span>{filtered.length} preguntas encontradas</span><button className="text-button" onClick={()=>{setParams({});setLimit(15);}}>Limpiar filtros</button></div><div className="question-grid">{filtered.slice(0,limit).map(q=><QuestionCard question={q} key={q.id}/>)}</div>{filtered.length>limit&&<div className="load-more"><button className="button secondary" onClick={()=>setLimit(n=>n+15)}>Ver más preguntas ({filtered.length-limit} restantes)</button></div>}{!filtered.length&&<EmptyState title="No hay preguntas con esos filtros">Probá otro tema o guardá alguna pregunta en favoritos.</EmptyState>}</>;
}
