import { describe, it, expect } from 'vitest';
import { lessons, lessonLoaders, questions, quizzes, units, stages, loadLesson } from './index';
import { splitSections } from '../lib/study';
describe('integridad del recorrido publicado',()=>{
 it('publica cinco etapas, veinte unidades y setenta lecciones con contenido',()=>{expect(stages).toHaveLength(5);expect(units).toHaveLength(20);expect(lessons).toHaveLength(70);expect(new Set(lessons.map(l=>l.id)).size).toBe(70);for(const u of units){const expected=u.id<=16?3:{17:4,18:9,19:5,20:4}[u.id as 17|18|19|20];expect(lessons.filter(l=>l.unitId===u.id),`unidad ${u.id}`).toHaveLength(expected);}expect(lessons.filter(l=>l.id.startsWith('kafka-'))).toHaveLength(22);for(const l of lessons){expect(lessonLoaders[`./lessons/${l.id}.md`]).toBeDefined();expect(l.objectives.length).toBeGreaterThan(0);expect(l.resources.length).toBeGreaterThan(0);for(const r of l.resources)expect(new URL(r.url).protocol).toBe('https:');}});
 it('las lecciones incluyen razonamiento, práctica, pista y solución',async()=>{for(const l of lessons){const text=await loadLesson(l.id);const headings=splitSections(text).map(s=>s.title);for(const title of ['Concepto','Ejemplo','En entrevista','Error frecuente','Práctica','Profundización'])expect(headings,`${l.id}: ${title}`).toContain(title);expect(text).toContain('### Pista');expect(text).toContain('### Solución');expect(text.split(/\s+/).length).toBeGreaterThan(230);expect((text.match(/^```/gm)||[]).length%2).toBe(0);}});
 it('las preguntas y quizzes apuntan a lecciones existentes y unidades coherentes',()=>{for(const item of [...questions,...quizzes]){const l=lessons.find(l=>l.id===item.lessonId);expect(l, item.id).toBeDefined();expect(l?.unitId,item.id).toBe(item.unitId);}expect(new Set(questions.map(q=>q.id)).size).toBe(questions.length);expect(new Set(questions.map(q=>q.prompt)).size).toBe(questions.length);for(const q of questions){expect(q.answer.length).toBeGreaterThan(50);expect(q.keyPoints.length).toBeGreaterThan(0);}});
 it('cada quiz tiene respuesta válida y explica todas las opciones',()=>{expect(quizzes).toHaveLength(40);for(const u of units)expect(quizzes.filter(q=>q.unitId===u.id)).toHaveLength(2);for(const q of quizzes){expect(q.correctIndex).toBeGreaterThanOrEqual(0);expect(q.correctIndex).toBeLessThan(q.options.length);expect(q.options).toHaveLength(4);for(const option of q.options)expect(option.explanation.length).toBeGreaterThan(20);}expect(new Set(quizzes.map(q=>q.correctIndex)).size).toBeGreaterThan(2);});
});
