import type { Lesson } from '../types';

const java={title:'Java 21: documentación oficial',url:'https://docs.oracle.com/en/java/javase/21/docs/api/'};
const spring={title:'Spring Boot: referencia oficial',url:'https://docs.spring.io/spring-boot/reference/'};
const postgres={title:'PostgreSQL: documentación oficial',url:'https://www.postgresql.org/docs/current/'};
const kafka={title:'Apache Kafka 3.9: diseño y garantías',url:'https://kafka.apache.org/39/design/design/'};
const flyway={title:'Flyway: documentación oficial',url:'https://documentation.red-gate.com/flyway/getting-started-with-flyway'};
const testcontainers={title:'Testcontainers for Java: documentación oficial',url:'https://java.testcontainers.org/'};
const redis={title:'Redis: cache-aside oficial',url:'https://redis.io/docs/latest/develop/use-cases/cache-aside/'};
const avro={title:'Apache Avro: documentación oficial',url:'https://avro.apache.org/docs/'};

export const expansionLessons: Lesson[] = [
 {id:'u04-d',unitId:4,title:'Patrones de algoritmos para entrevistas',description:'Two pointers, sliding window, HashMap, pilas y colas con código y complejidad.',minutes:10,tags:['two pointers','sliding window','HashMap','stack','queue','complejidad'],objectives:['Reconocer el patrón antes de codificar','Justificar tiempo y espacio','Probar casos límite'],prerequisites:['u04-a','u03-a'],resources:[java]},
 {id:'u11-d',unitId:11,title:'SQL de entrevista y diagnóstico',description:'Normalización, constraints, índices y EXPLAIN para razonar antes de optimizar.',minutes:10,tags:['normalización','constraints','índice compuesto','EXPLAIN','deadlock'],objectives:['Proteger integridad desde el esquema','Leer un plan de consulta','Explicar un deadlock'],prerequisites:['u11-a','u11-c'],resources:[postgres]},
 {id:'u21-a',unitId:21,title:'Entorno reproducible y terminal',description:'JDK, variables de entorno, PATH y comandos mínimos para ejecutar Java sin misterio.',minutes:8,tags:['terminal','JAVA_HOME','PATH','variables de entorno','Maven'],objectives:['Separar configuración del sistema y del proyecto','Inspeccionar versión y proceso','Evitar secretos en comandos'],prerequisites:['u01-a'],resources:[java]},
 {id:'u21-b',unitId:21,title:'Debugging con una hipótesis',description:'Breakpoints, pasos y observación de estado sin convertir el debugger en adivinanza.',minutes:8,tags:['debugger','breakpoint','step over','step into','watch'],objectives:['Formular una hipótesis comprobable','Elegir breakpoint y paso','Inspeccionar el estado relevante'],prerequisites:['u21-a','u02-b'],resources:[java]},
 {id:'u21-c',unitId:21,title:'Stack traces y logs iniciales',description:'Leé una excepción desde la causa y registrá evidencia útil para investigar.',minutes:8,tags:['stack trace','logging','causa','nivel de log','correlation id'],objectives:['Encontrar la causa raíz','Distinguir señal y ruido','Registrar contexto seguro'],prerequisites:['u21-b','u05-a'],resources:[java]},
 {id:'u22-a',unitId:22,title:'Stack, heap y referencias',description:'Relacioná alcance, objetos y referencias sin confundir la pila JVM con un Stack de datos.',minutes:9,tags:['stack','heap','referencia','escape analysis','memoria'],objectives:['Ubicar variables y objetos conceptualmente','Explicar paso por valor','Diagnosticar referencias retenidas'],prerequisites:['u02-b'],resources:[java]},
 {id:'u22-b',unitId:22,title:'GC, mutabilidad y copias defensivas',description:'El garbage collector libera objetos inalcanzables; no corrige diseños que retienen estado.',minutes:9,tags:['GC','fuga de memoria','mutabilidad','copia defensiva','inmutabilidad'],objectives:['Distinguir fuga y presión de memoria','Evitar exponer colecciones mutables','Elegir una copia defensiva'],prerequisites:['u22-a','u03-a'],resources:[java]},
 {id:'u22-c',unitId:22,title:'Tiempo y entradas robustas',description:'Modelá fechas y zonas horarias, y validá datos antes de que lleguen al dominio.',minutes:9,tags:['Instant','ZoneId','validación','null','límite de entrada'],objectives:['Elegir un tipo temporal adecuado','Evitar null ambiguo','Definir límites de entrada'],prerequisites:['u22-b','u06-c'],resources:[java]},
 {id:'u23-a',unitId:23,title:'APIs que pueden evolucionar',description:'Paginación, filtros, orden y versionado sin romper consumidores por accidente.',minutes:9,tags:['paginación','cursor','filtros','versionado','compatibilidad'],objectives:['Diseñar una consulta paginada','Distinguir offset y cursor','Planificar una evolución compatible'],prerequisites:['u09-a','u10-c'],resources:[spring]},
 {id:'u23-b',unitId:23,title:'Errores, migraciones y preparación',description:'Problem Details, Flyway y health checks para hacer visible el estado real de una API.',minutes:9,tags:['ProblemDetail','Flyway','migration','readiness','Actuator'],objectives:['Devolver errores accionables','Versionar cambios de esquema','Separar liveness de readiness'],prerequisites:['u10-b','u11-c'],resources:[spring,postgres,flyway]},
 {id:'u23-c',unitId:23,title:'Pruebas de integración operables',description:'Testcontainers y cierre gradual para probar dependencias reales y detener procesos con seguridad.',minutes:9,tags:['Testcontainers','integración','graceful shutdown','pool','health check'],objectives:['Distinguir test unitario e integración','Aislar dependencias efímeras','Explicar un cierre gradual'],prerequisites:['u13-a','u23-b'],resources:[spring,testcontainers]},
 {id:'u24-a',unitId:24,title:'ADRs y monolito modular',description:'Registrá decisiones y mantené límites claros antes de separar un sistema en servicios.',minutes:9,tags:['ADR','monolito modular','acoplamiento','límites','arquitectura'],objectives:['Escribir una decisión verificable','Detectar un límite de módulo','Comparar costo de extracción'],prerequisites:['u14-a','u14-c'],resources:[spring]},
 {id:'u24-b',unitId:24,title:'Timeouts, retries y circuit breakers',description:'Protegé una operación remota sin convertir un fallo transitorio en una tormenta de reintentos.',minutes:10,tags:['timeout','retry','backoff','circuit breaker','bulkhead'],objectives:['Definir un timeout explícito','Clasificar errores reintentables','Limitar recursos compartidos'],prerequisites:['u16-b','u24-a'],resources:[spring]},
 {id:'u24-c',unitId:24,title:'Caché y decisiones medibles',description:'Usá cache-aside con límites de frescura, métricas y una estrategia de invalidación.',minutes:10,tags:['Redis','cache-aside','TTL','cache stampede','métricas'],objectives:['Definir clave, TTL e invalidación','Reconocer un stampede','Medir antes de optimizar'],prerequisites:['u16-b','u24-b'],resources:[spring,redis]},
 {id:'u25-a',unitId:25,title:'Contratos de eventos que evolucionan',description:'Definí schemas y reglas de compatibilidad para que productores y consumidores puedan cambiar en distintos momentos.',minutes:10,tags:['Avro','Protobuf','Schema Registry','compatibilidad','contrato'],objectives:['Distinguir formato, schema y contrato','Elegir una regla de compatibilidad','Planificar una evolución segura'],prerequisites:['kafka-core-concepts'],resources:[kafka,avro,{title:'Confluent Schema Registry: compatibilidad','url':'https://docs.confluent.io/platform/current/schema-registry/fundamentals/schema-evolution.html'}]},
 {id:'u25-b',unitId:25,title:'Retry topics, DLQ y reproceso',description:'Clasificá fallos, limitá reintentos y diseñá una recuperación observable sin asumir orden ni efectos únicos.',minutes:10,tags:['retry topic','DLQ','reproceso','idempotencia','backoff'],objectives:['Distinguir fallos transitorios y permanentes','Definir retry y DLQ con límites','Planificar reproceso seguro'],prerequisites:['kafka-delivery-semantics'],resources:[kafka]},
 {id:'u25-c',unitId:25,title:'Kafka Streams y procesamiento con estado',description:'Modelá transformaciones, ventanas y estado local para decidir cuándo Streams encaja.',minutes:10,tags:['Kafka Streams','KStream','KTable','ventanas','estado'],objectives:['Distinguir KStream y KTable','Explicar estado, ventanas y eventos tardíos','Reconocer las garantías y límites de Streams'],prerequisites:['kafka-retention-compaction'],resources:[{title:'Apache Kafka Streams 3.9: guía de desarrollador','url':'https://kafka.apache.org/39/streams/developer-guide/'}]},
 {id:'u25-d',unitId:25,title:'Seguridad: TLS, SASL y ACL',description:'Separá cifrado, autenticación y autorización para conceder a cada cliente solo el acceso requerido.',minutes:10,tags:['seguridad','TLS','SASL','ACL','credenciales'],objectives:['Explicar qué protege TLS','Distinguir autenticación SASL de autorización ACL','Proponer permisos mínimos por cliente'],prerequisites:['kafka-core-concepts'],resources:[{title:'Apache Kafka 3.9: seguridad','url':'https://kafka.apache.org/39/security/security-overview/'}]},
 {id:'u25-e',unitId:25,title:'Observabilidad y capacidad de Kafka',description:'Interpretá lag junto con tasas, particiones y salud del clúster para encontrar límites reales.',minutes:10,tags:['observabilidad','consumer lag','métricas','capacidad','particiones'],objectives:['Interpretar lag por tendencia y partición','Relacionar métricas de broker y consumer','Diagnosticar límites de capacidad antes de escalar'],prerequisites:['kafka-rebalance-scaling'],resources:[{title:'Apache Kafka 3.9: métricas de monitoreo','url':'https://kafka.apache.org/39/operations/monitoring/'}]},
];
