import type { Question, QuizQuestion } from '../types';
import { unitById } from './units';

type Spec={id:string;unitId:number;lessonId:string;prompt:string;short:string;detail:string;points:string[]};
function question(spec:Spec):Question {const unit=unitById.get(spec.unitId);if(!unit)throw new Error(`Unidad inexistente: ${spec.unitId}`);return {id:`q-${spec.id}`,unitId:spec.unitId,lessonId:spec.lessonId,prompt:spec.prompt,shortAnswer:spec.short,answer:`${spec.short}\n\n${spec.detail}`,keyPoints:spec.points,level:unit.level};}

export const expansionQuestions: Question[] = [
 question({id:'algo-two-pointers',unitId:4,lessonId:'u04-d',prompt:'¿Cuándo elegirías el patrón two pointers?',short:'Cuando dos posiciones pueden avanzar sobre una estructura ordenada o una relación de extremos sin reiniciar el recorrido.',detail:'Explicaría la precondición, el invariante de cada puntero y el costo. En un array ordenado puedo mover izquierda o derecha según la suma; si el array no está ordenado, debo justificar ordenar o usar otro enfoque.',points:['Precondición de orden o relación','Invariante de punteros','Tiempo y espacio']}),
 question({id:'algo-sliding-window',unitId:4,lessonId:'u04-d',prompt:'¿Qué invariante mantiene una sliding window?',short:'Mantiene un intervalo que cumple una regla mientras sus extremos avanzan sin retroceder.',detail:'Al agregar el elemento derecho actualizo el estado; si la regla deja de cumplirse, avanzo izquierda hasta restaurarla. Cada extremo avanza como máximo n veces, por lo que el recorrido suele ser lineal.',points:['Intervalo válido','Estado incremental','O(n) habitual']}),
 question({id:'algo-frequency-map',unitId:4,lessonId:'u04-d',prompt:'¿Para qué sirve un HashMap de frecuencias?',short:'Para contar o localizar valores y evitar comparar cada elemento contra todos los demás.',detail:'El mapa permite actualizar una frecuencia o última posición al recorrer la entrada. El acceso es O(1) promedio; explicaría la complejidad total, el espacio proporcional a claves distintas y los casos de colisión como detalle de implementación.',points:['Conteo incremental','Costo promedio','Espacio por claves']}),
 question({id:'algo-stack-queue',unitId:4,lessonId:'u04-d',prompt:'¿Cómo distinguís una pila de una cola en un problema de entrevista?',short:'La pila procesa el último elemento agregado; la cola procesa el primero.',detail:'Usaría pila para delimitadores, deshacer o próximo mayor; una cola para orden de llegada y BFS. No elegiría por el nombre de la clase sino por el orden de salida que exige el problema.',points:['LIFO y FIFO','Caso de uso','Orden de salida']}),
 question({id:'sql-normalization',unitId:11,lessonId:'u11-d',prompt:'¿Qué problema intenta evitar la normalización?',short:'Reduce duplicación y anomalías de actualización al separar hechos con dependencias distintas.',detail:'No significa que toda lectura deba hacer muchos joins. Mantengo el modelo fuente coherente y creo proyecciones o índices cuando una consulta real los necesita y están medidos.',points:['Evitar anomalías','Modelo fuente','Lecturas medidas']}),
 question({id:'sql-composite-index',unitId:11,lessonId:'u11-d',prompt:'¿Cómo decidís el orden de un índice compuesto?',short:'Parto de filtros, orden y selectividad de las consultas reales, no del orden visual de las columnas.',detail:'El prefijo del índice debe servir a la consulta. Verifico con EXPLAIN ANALYZE, considero cardinalidad y costo de escritura, y no asumo que un índice ayuda a cualquier combinación de columnas.',points:['Consulta real','Prefijo del índice','Plan de ejecución']}),
 question({id:'sql-explain',unitId:11,lessonId:'u11-d',prompt:'¿Qué revisás en EXPLAIN ANALYZE?',short:'Comparo filas estimadas y reales, método de acceso, joins, ordenamientos y tiempo de cada operación.',detail:'Una diferencia grande entre estimación y realidad puede indicar estadísticas insuficientes o una condición difícil de estimar. Primero entiendo el plan y los datos; luego propongo un cambio pequeño y lo vuelvo a medir.',points:['Estimación frente a realidad','Operador costoso','Medir antes y después']}),
 question({id:'sql-deadlock',unitId:11,lessonId:'u11-d',prompt:'¿Qué harías ante un deadlock?',short:'Revisaría transacciones, orden de bloqueo y consultas, y aplicaría un reintento limitado solo si el caso es seguro.',detail:'Un deadlock aparece cuando transacciones esperan recursos en ciclo. Reducir alcance y adquirir recursos en orden consistente suele ser mejor que aumentar reintentos sin límite.',points:['Orden de bloqueo','Transacción corta','Reintento seguro']}),
 question({id:'env-java-home',unitId:21,lessonId:'u21-a',prompt:'¿Qué comprobarías si Maven compila con otra versión de Java?',short:'Comprobaría java -version, mvn -v, JAVA_HOME, PATH, toolchains y configuración del IDE.',detail:'La evidencia muestra qué ejecutable se usa realmente. Alineo la versión declarada por el proyecto y documento el requisito; no cambio código hasta separar un problema de entorno de uno de compilación.',points:['Versiones efectivas','Fuente de verdad','Entorno reproducible']}),
 question({id:'env-secrets',unitId:21,lessonId:'u21-a',prompt:'¿Dónde deberían vivir credenciales de desarrollo?',short:'Fuera del repositorio, inyectadas por variables de entorno o un mecanismo de secretos apropiado.',detail:'El README puede describir nombres y ejemplo sin valores reales. Un .gitignore no elimina un secreto ya publicado ni reemplaza revocarlo si se filtró.',points:['No versionar secretos','Variables o gestor','Revocar filtraciones']}),
 question({id:'debug-hypothesis',unitId:21,lessonId:'u21-b',prompt:'¿Cómo usarías un debugger sin adivinar?',short:'Partiría de un síntoma reproducible, una hipótesis y un breakpoint donde la evidencia pueda confirmarla o descartarla.',detail:'Inspecciono entradas, transición de estado e invariante. Una vez hallada la causa agrego una prueba para que el aprendizaje no dependa de repetir la sesión manual.',points:['Síntoma reproducible','Hipótesis','Prueba posterior']}),
 question({id:'debug-steps',unitId:21,lessonId:'u21-b',prompt:'¿Qué diferencia hay entre step over y step into?',short:'Step over ejecuta una llamada sin entrar; step into sigue su implementación.',detail:'Elijo según dónde está la hipótesis. Step out vuelve al llamador, y un breakpoint condicional reduce ruido cuando un loop procesa muchos elementos.',points:['Nivel de inspección','Hipótesis','Reducir ruido']}),
 question({id:'trace-root-cause',unitId:21,lessonId:'u21-c',prompt:'¿Cómo leés un stack trace con excepciones encadenadas?',short:'Busco la causa más profunda y la primera línea relevante de mi código para entender qué operación la provocó.',detail:'No corrijo solo el mensaje exterior. Conservo tipo, causa y contexto seguro en logs, pero no expongo detalles internos o secretos en una respuesta HTTP.',points:['Causa raíz','Marco propio','Contexto seguro']}),
 question({id:'logging-levels',unitId:21,lessonId:'u21-c',prompt:'¿Qué diferencia básica hay entre INFO, WARN y ERROR?',short:'INFO registra hitos, WARN una degradación o condición inesperada y ERROR un fallo que necesita atención.',detail:'El nivel no reemplaza el manejo del error. Un log útil incluye operación e identificador seguro, y evita tokens, contraseñas o cuerpos sensibles.',points:['Señal operativa','Contexto mínimo','Sin secretos']}),
 question({id:'memory-reference',unitId:22,lessonId:'u22-a',prompt:'¿Java pasa objetos por referencia?',short:'Java pasa argumentos por valor; cuando el valor es una referencia, ambos pueden apuntar al mismo objeto.',detail:'Mutar el objeto se observa desde el llamador, pero reasignar el parámetro solo cambia la copia local. Esta diferencia debe explicarse con un ejemplo simple.',points:['Paso por valor','Referencia copiada','Mutación frente a reasignación']}),
 question({id:'memory-leak',unitId:22,lessonId:'u22-a',prompt:'¿Cómo puede haber fuga de memoria en Java con garbage collector?',short:'Cuando el programa conserva referencias a objetos que ya no necesita.',detail:'Cachés sin límite, listeners no removidos, colecciones estáticas o tareas largas pueden mantener alcanzables objetos. El GC no puede liberar algo que sigue referenciado.',points:['Alcanzabilidad','Retención accidental','Medir referencias']}),
 question({id:'defensive-copy',unitId:22,lessonId:'u22-b',prompt:'¿Cuándo harías una copia defensiva?',short:'Cuando una clase recibe o expone datos mutables y debe proteger sus invariantes.',detail:'List.copyOf puede fijar la vista publicada; una operación de dominio controla cómo se agregan elementos. Evalúo costo y propiedad del dato antes de copiar estructuras grandes.',points:['Frontera de mutabilidad','Invariantes','Costo de copia']}),
 question({id:'gc-final',unitId:22,lessonId:'u22-b',prompt:'¿final evita una fuga de memoria?',short:'No: final evita reasignar una referencia, pero no vuelve inmutable el objeto ni lo hace inalcanzable.',detail:'La corrección requiere remover la referencia innecesaria, acotar una caché o cerrar un ciclo de vida. Llamar al GC no es una estrategia de diseño.',points:['Referencia fija','Objeto mutable','Ciclo de vida']}),
 question({id:'time-types',unitId:22,lessonId:'u22-c',prompt:'¿Qué tipos elegirías para cumpleaños, pago y turno local?',short:'LocalDate para cumpleaños, Instant para pago y un tipo local con ZoneId acordada para el turno.',detail:'Cada dato expresa un significado distinto. Convertir a UTC sin saber qué representa la fecha puede cambiar su interpretación de negocio.',points:['Significado temporal','Zona explícita','Conversión consciente']}),
 question({id:'input-boundary',unitId:22,lessonId:'u22-c',prompt:'¿La validación del controller reemplaza las invariantes del dominio?',short:'No; filtra formato y límites de entrada, mientras el dominio protege reglas de negocio.',detail:'Otros adaptadores también pueden invocar el caso de uso. Por eso valido temprano para proteger recursos y vuelvo a validar la regla que mantiene el estado válido.',points:['Dos fronteras','Formato y negocio','Otros adaptadores']}),
 question({id:'api-cursor',unitId:23,lessonId:'u23-a',prompt:'¿Qué ventaja tiene un cursor frente a offset?',short:'Un cursor puede ser más estable ante inserciones y más eficiente en recorridos grandes cuando se apoya en un orden definido.',detail:'Debe incluir una clave de desempate y no se presenta como dato de negocio. Offset sigue siendo válido para casos simples, con sus límites documentados.',points:['Orden estable','Cambios entre páginas','Contrato del cursor']}),
 question({id:'api-problem-details',unitId:23,lessonId:'u23-b',prompt:'¿Qué aporta Problem Details?',short:'Un formato consistente para comunicar tipo, título, estado y detalle seguro de un error HTTP.',detail:'Permite a un cliente distinguir validación, ausencia o conflicto sin conocer la excepción interna. El handler global traduce fronteras; no debe ocultar errores de programación.',points:['Contrato de error','Detalle seguro','Frontera HTTP']}),
 question({id:'api-migration',unitId:23,lessonId:'u23-b',prompt:'¿Cómo desplegarías una columna obligatoria con datos existentes?',short:'Primero agregaría una columna compatible, migraría escritura y datos, y solo después impondría la restricción.',detail:'Flyway registra pasos versionados. La secuencia evita que aplicaciones antiguas fallen durante una entrega gradual y permite revisar el estado del esquema.',points:['Cambio aditivo','Backfill','Restricción final']}),
 question({id:'api-readiness',unitId:23,lessonId:'u23-b',prompt:'¿Cómo distinguís liveness y readiness?',short:'Liveness indica si el proceso debe reiniciarse; readiness indica si puede recibir tráfico.',detail:'Una instancia puede estar viva y no lista porque faltan migraciones o una dependencia esencial. No uso el mismo check para decisiones operativas distintas.',points:['Proceso vivo','Servicio listo','Dependencias']}),
 question({id:'api-testcontainers',unitId:23,lessonId:'u23-c',prompt:'¿Qué demuestra Testcontainers que un mock no demuestra?',short:'Que la aplicación integra con una dependencia real y su configuración, protocolo o esquema.',detail:'Lo uso para fronteras críticas como PostgreSQL o Kafka. Mantengo tests unitarios para reglas rápidas y dejo datos aislados por prueba.',points:['Dependencia real','Frontera crítica','Datos aislados']}),
 question({id:'api-graceful-shutdown',unitId:23,lessonId:'u23-c',prompt:'¿Qué busca un graceful shutdown?',short:'Dejar de aceptar trabajo nuevo y terminar el trabajo en curso dentro de un límite antes de cerrar recursos.',detail:'No vuelve atómicas operaciones distribuidas. En consumers también reviso qué mensajes pueden repetirse y cómo la idempotencia protege efectos posteriores.',points:['No aceptar trabajo nuevo','Límite temporal','Idempotencia']}),
 question({id:'adr',unitId:24,lessonId:'u24-a',prompt:'¿Qué debe contener un ADR útil?',short:'Contexto, decisión, alternativas, consecuencias y condición para revisarla.',detail:'El objetivo es conservar el razonamiento, no declarar una verdad permanente. Debe ser breve y permitir entender qué cambió si la decisión se revisa.',points:['Contexto','Trade-offs','Revisión']}),
 question({id:'modular-monolith',unitId:24,lessonId:'u24-a',prompt:'¿Cuándo preferirías un monolito modular?',short:'Cuando el dominio aún cambia y no hay una necesidad demostrada de despliegue o escala independiente.',detail:'Mantengo módulos y contratos explícitos sin sumar red, observabilidad distribuida ni consistencia eventual antes de necesitarlas.',points:['Límites internos','Costo operacional','Evolución gradual']}),
 question({id:'timeout-retry',unitId:24,lessonId:'u24-b',prompt:'¿Qué condiciones debe cumplir un retry?',short:'Debe apuntar a un fallo transitorio, tener límite y ser seguro para el efecto que puede repetir.',detail:'Defino timeout, backoff y máximo de intentos. No reintento validaciones ni efectos no idempotentes sin una clave o diseño que controle duplicados.',points:['Error transitorio','Backoff limitado','Idempotencia']}),
 question({id:'circuit-breaker',unitId:24,lessonId:'u24-b',prompt:'¿Qué problema evita un circuit breaker?',short:'Evita seguir esperando o cargando una dependencia que está fallando de manera sostenida.',detail:'Abre según una política medida y permite recuperación controlada. No sustituye timeouts, límites de concurrencia ni una respuesta de negocio definida.',points:['Fallo sostenido','Rechazo rápido','Métricas']}),
 question({id:'cache-aside',unitId:24,lessonId:'u24-c',prompt:'¿Cómo funciona cache-aside?',short:'La aplicación consulta caché, carga desde la fuente en un miss y almacena el resultado según una política.',detail:'Defino clave, TTL, invalidación y comportamiento si la caché falla. La caché acelera lecturas, pero no elimina decisiones de consistencia.',points:['Miss controlado','TTL e invalidación','Fuente de verdad']}),
 question({id:'cache-stampede',unitId:24,lessonId:'u24-c',prompt:'¿Qué es un cache stampede?',short:'Un pico de solicitudes que vence o pierde la misma clave y golpea la fuente simultáneamente.',detail:'Puedo dispersar expiraciones, usar bloqueo por clave o recálculo anticipado. La técnica elegida depende del costo de recomputar y del dato tolerablemente viejo.',points:['Miss simultáneo','Mitigación','Costo y frescura']}),
 question({id:'schema-registry',unitId:25,lessonId:'u25-a',prompt:'¿Qué aporta un Schema Registry?',short:'Centraliza versiones de schemas y permite verificar compatibilidad antes de publicar cambios.',detail:'No garantiza que el significado de un campo siga siendo correcto. Combino compatibilidad técnica con ejemplos, revisión de consumidores y pruebas de integración.',points:['Versiones','Compatibilidad','Semántica']}),
 question({id:'event-compatibility',unitId:25,lessonId:'u25-a',prompt:'¿Qué cambio suele ser más seguro en un evento?',short:'Agregar un campo opcional documentado con valor por defecto compatible.',detail:'Renombrar o cambiar el significado de un campo puede romper consumidores aunque el formato siga siendo válido. La evolución se planifica como contrato compartido.',points:['Cambio aditivo','Campo opcional','Consumidores']}),
 question({id:'retry-topic',unitId:25,lessonId:'u25-b',prompt:'¿Para qué sirve un retry topic?',short:'Para reintentar eventos diferidos sin bloquear el consumo principal ni perder contexto.',detail:'Defino cantidad de intentos, backoff, clasificación de errores y paso a DLQ. No uso reintentos infinitos para fallos permanentes.',points:['Aislar flujo','Backoff','Política explícita']}),
 question({id:'dlq',unitId:25,lessonId:'u25-b',prompt:'¿Qué información necesita una DLQ para ser útil?',short:'Evento original, causa, topic, partición, offset, versión e identificador de correlación.',detail:'Además necesita responsable, alerta y procedimiento de replay. Sin contexto ni proceso, la DLQ solo posterga un fallo y puede acumular datos imposibles de investigar.',points:['Evidencia','Responsable','Reproceso']}),
 question({id:'kafka-security',unitId:25,lessonId:'u25-c',prompt:'¿Cómo se complementan TLS, SASL y ACLs?',short:'TLS cifra, SASL autentica y ACLs autorizan acciones sobre recursos Kafka.',detail:'Uso credenciales por servicio y permisos mínimos para topics y grupos. Autenticar no significa que un cliente pueda leer o escribir cualquier canal.',points:['Cifrado','Autenticación','Autorización mínima']}),
 question({id:'kafka-lag',unitId:25,lessonId:'u25-c',prompt:'¿Qué contexto necesitás para interpretar consumer lag?',short:'Tasa de llegada, tasa de proceso, particiones, tiempo de recuperación y tendencia del lag.',detail:'Un pico breve puede ser aceptable; un crecimiento sostenido indica capacidad o fallo. No escalo consumidores por encima de las particiones esperando paralelismo adicional.',points:['Tendencia','Capacidad','Particiones']}),
];

type Choice=[string,string];
function quiz(id:string,unitId:number,lessonId:string,prompt:string,correctIndex:number,choices:Choice[]):QuizQuestion{return{id:`quiz-${id}`,unitId,lessonId,prompt,correctIndex,options:choices.map(([text,explanation])=>({text,explanation}))};}
export const expansionQuizzes: QuizQuestion[] = [
 quiz('algo-window',4,'u04-d','¿Qué permite que una sliding window sea O(n) en un recorrido?',0,[['Cada puntero avanza sin retroceder','Izquierda y derecha recorren la entrada como máximo una vez cada uno.'],['Ordenar siempre la entrada','Ordenar puede ser innecesario y agrega otro costo.'],['Usar recursión','La recursión no determina por sí sola el costo del algoritmo.'],['Guardar todos los subarreglos','Eso suele aumentar espacio y no mantiene una ventana.']]),
 quiz('sql-explain',11,'u11-d','¿Qué dato de EXPLAIN ANALYZE merece atención al diagnosticar?',2,[['El nombre de la tabla solamente','El nombre no explica el costo ni el acceso elegido.'],['La versión de Java del cliente','No forma parte del plan de ejecución SQL.'],['Diferencia entre filas estimadas y reales','Una diferencia grande puede revelar estadísticas o supuestos incorrectos.'],['El color del cliente SQL','La interfaz visual no cambia el plan.']]),
 quiz('debug-breakpoint',21,'u21-b','¿Qué hace más útil a un breakpoint?',1,[['Ponerlo en cada línea','Genera ruido y no prueba una hipótesis.'],['Ubicarlo donde puede verificarse una hipótesis','Permite observar entrada, estado o transición relevante.'],['Modificar variables hasta que pase','Puede ocultar la causa real del fallo.'],['Evitar tests automatizados','El debugging debe terminar en una protección repetible.']]),
 quiz('memory-copy',22,'u22-b','¿Qué protege List.copyOf al publicar una colección?',3,[['Que los objetos internos sean inmutables','La copia no transforma los elementos mutables.'],['Que el GC la libere de inmediato','La alcanzabilidad sigue definiendo el ciclo de vida.'],['Que todos los hilos puedan escribir','La colección resultante no admite modificaciones.'],['Que el llamador no modifique la estructura publicada','Evita cambios estructurales externos sobre esa colección.']]),
 quiz('api-readiness',23,'u23-b','¿Qué expresa mejor readiness?',0,[['La instancia puede recibir tráfico útil','Incluye dependencias necesarias y preparación para servir.'],['El proceso tiene un PID','Eso no confirma que pueda operar correctamente.'],['La API siempre responde 200','Los errores de negocio siguen siendo posibles.'],['La base ya no tiene datos','La existencia de datos no define disponibilidad.']]),
 quiz('resilience-retry',24,'u24-b','¿Cuándo es razonable reintentar una operación?',2,[['Ante cualquier respuesta 400','Es un error de solicitud, no un fallo transitorio.'],['Sin límite mientras la dependencia falle','Amplifica carga y puede bloquear recursos.'],['Ante un fallo transitorio con operación segura','Debe combinar límite, backoff e idempotencia cuando corresponda.'],['Cuando no existe timeout','El timeout debe definirse antes de plantear reintentos.']]),
 quiz('kafka-schema',25,'u25-a','¿Qué cambio de evento suele ser más compatible?',1,[['Cambiar el significado de un campo existente','El formato puede aceptar el campo, pero el negocio se rompe.'],['Agregar un campo opcional documentado','Permite que consumidores existentes lo ignoren según la política acordada.'],['Eliminar un campo que usan consumidores','Rompe su deserialización o lógica.'],['Renombrar sin transición','Equivale a quitar y agregar contrato de forma incompatible.']]),
 quiz('kafka-dlq',25,'u25-b','¿Qué no debería faltar en una DLQ?',3,[['Solo el payload original','Sin causa u origen es difícil investigar o reproducir.'],['Un reintento infinito','Una DLQ existe para aislar fallos persistentes.'],['Una credencial de administrador','Las credenciales no son evidencia del fallo.'],['Causa y metadatos de origen','Topic, partición, offset y correlación permiten investigar y reprocesar.']]),
 quiz('env-version',21,'u21-a','¿Qué comando aporta evidencia sobre el JDK que usa Maven?',1,[['git status','Muestra cambios de Git, no el runtime de Maven.'],['mvn -v','Informa versión de Maven y Java efectivos.'],['java --enable-preview','No inspecciona la configuración elegida por Maven.'],['docker ps','Muestra contenedores, no el toolchain local.']]),
 quiz('time-instant',22,'u22-c','¿Qué tipo representa mejor un pago ocurrido globalmente?',0,[['Instant','Representa un punto concreto de la línea temporal.'],['LocalDate','No contiene hora ni zona.'],['String','Pierde semántica y validación temporal.'],['ZoneId','Describe una zona, no un momento.']]),
 quiz('api-cursor',23,'u23-a','¿Qué necesita un cursor de paginación para ser claro?',2,[['Solo el tamaño de página','No indica desde qué posición continuar.'],['Un contador mutable global','Introduce estado compartido y difícil de escalar.'],['Un orden estable y clave de desempate','Permite continuar el recorrido con una regla documentada.'],['La contraseña del usuario','No forma parte del contrato de paginación.']]),
 quiz('cache-stampede',24,'u24-c','¿Qué ayuda a reducir un cache stampede?',1,[['Eliminar todo TTL','Dejar datos sin expiración no define frescura ni evita otros misses.'],['Dispersar expiraciones o coordinar el recálculo','Reduce que muchas solicitudes lleguen a la fuente al mismo tiempo.'],['Reintentar cada miss sin límite','Amplifica la carga sobre una fuente ya presionada.'],['Guardar las contraseñas en la caché','No resuelve el patrón de expiración y expone secretos.']]),
];
