import type { Lesson } from '../types';

const java = { title: 'Learn Java · documentación oficial', url: 'https://dev.java/learn/' };
const git = { title: 'Referencia oficial de Git', url: 'https://git-scm.com/docs' };
const maven = { title: 'Maven: dependencias y scopes', url: 'https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html' };
const comparator = { title: 'Contrato de Comparator · Java 21', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Comparator.html' };

export const fundamentalLessons: Lesson[] = [
  { id: 'u01-a', unitId: 1, title: 'Del código a la JVM: JDK y Maven', description: 'Entendé qué compila, qué ejecuta y cómo se construye una aplicación reproducible.', minutes: 7, tags: ['JDK','JVM','Maven','scopes','compilación'], objectives: ['Distinguir JDK, JVM y bytecode','Elegir scopes de dependencias','Recorrer el ciclo de Maven'], prerequisites: ['Ninguno'], resources: [java,maven] },
  { id: 'u01-b', unitId: 1, title: 'Git y Git Flow sin memorizar a ciegas', description: 'Ramas, revisión y recuperación de cambios con un modelo mental claro.', minutes: 10, tags: ['Git','Git Flow','rebase','stash','pull request'], objectives: ['Distinguir working tree, index e historial','Resolver conflictos y elegir comandos','Explicar Git Flow y revisión'], prerequisites: ['u01-a'], resources: [git] },
  { id: 'u01-c', unitId: 1, title: 'Scrum, entregas y versiones', description: 'Entendé Scrum como marco de trabajo y conectá un incremento con una entrega verificable.', minutes: 6, tags: ['Scrum','sprint','incremento','SemVer','CI'], objectives: ['Explicar roles, eventos y artefactos','Aplicar versionado semántico','Definir una entrega comprobable'], prerequisites: ['u01-b'], resources: [git,maven] },
  { id: 'u02-a', unitId: 2, title: 'Tipos, control de flujo, Strings y wrappers', description: 'La base para leer Java y detectar sorpresas de igualdad, null y números.', minutes: 8, tags: ['primitivos','String','wrappers','autoboxing','unboxing'], objectives: ['Elegir tipos y estructuras de control','Comparar Strings por contenido','Reconocer riesgos del unboxing'], prerequisites: ['u01-a'], resources: [java] },
  { id: 'u02-b', unitId: 2, title: 'Objetos que cuidan sus reglas', description: 'Clases, constructores y encapsulación a través de un inventario pequeño.', minutes: 7, tags: ['POO','encapsulación','constructores','static','final'], objectives: ['Proteger invariantes con métodos','Distinguir estado de clase e instancia','Entender referencias final'], prerequisites: ['u02-a'], resources: [java] },
  { id: 'u02-c', unitId: 2, title: 'Interfaces, abstracción y polimorfismo', description: 'Modelá contratos y reemplazá implementaciones sin cambiar a sus consumidores.', minutes: 8, tags: ['interfaces','clase abstracta','polimorfismo','overriding','equals'], objectives: ['Elegir interfaz o clase abstracta','Distinguir sobrecarga y sobrescritura','Separar identidad de igualdad'], prerequisites: ['u02-b'], resources: [java] },
  { id: 'u03-a', unitId: 3, title: 'Elegir la colección adecuada', description: 'List, Set, Map y Queue según lo que necesitás hacer con tus datos.', minutes: 8, tags: ['Collections','List','Set','Map','Queue','HashMap','ArrayList'], objectives: ['Elegir una colección por sus operaciones','Explicar orden, duplicados y mutabilidad','Reconocer costos habituales'], prerequisites: ['u02-c'], resources: [java] },
  { id: 'u03-b', unitId: 3, title: 'Generics y wildcards con sentido', description: 'Reutilizá código manteniendo verificaciones de tipos en compilación.', minutes: 8, tags: ['generics','wildcards','PECS','type erasure'], objectives: ['Definir métodos genéricos','Aplicar extends y super','Reconocer invariancia y borrado de tipos'], prerequisites: ['u03-a'], resources: [java] },
  { id: 'u03-c', unitId: 3, title: 'Comparable, Comparator e igualdad', description: 'Ordená pedidos, resolvé empates y entendé por qué equals y hashCode van juntos.', minutes: 10, tags: ['Comparable','Comparator','equals','hashCode','TreeSet','ordenamiento'], objectives: ['Componer criterios de orden','Respetar igualdad y hash','Detectar pérdida de elementos en TreeSet'], prerequisites: ['u03-b'], resources: [java,comparator] },
  { id: 'u04-a', unitId: 4, title: 'Big O, búsqueda y fusión de arrays', description: 'Razoná sobre crecimiento y resolvé la fusión ordenada sin volver a ordenar.', minutes: 10, tags: ['Big O','búsqueda binaria','búsqueda lineal','arrays','merge'], objectives: ['Estimar tiempo y espacio','Explicar la precondición de búsqueda binaria','Fusionar arrays en una pasada'], prerequisites: ['u03-a'], resources: [java] },
  { id: 'u04-b', unitId: 4, title: 'Ordenamiento: bubble, quicksort y JDK', description: 'Compará algoritmos por costo, estabilidad y condiciones de uso.', minutes: 9, tags: ['bubble sort','quicksort','estabilidad','Arrays.sort'], objectives: ['Seguir intercambios y particiones','Distinguir promedio y peor caso','Usar ordenamiento del JDK'], prerequisites: ['u04-a','u03-c'], resources: [java,comparator] },
  { id: 'u04-c', unitId: 4, title: 'Recursión, árboles y heaps', description: 'Casos base, factorial seguro y estructuras para jerarquías y prioridades.', minutes: 9, tags: ['recursión','factorial','árboles','heap','PriorityQueue'], objectives: ['Construir una recursión que termina','Comparar árbol y heap','Resolver factorial con límites'], prerequisites: ['u04-a'], resources: [java] },
  { id: 'u08-a', unitId: 5, title: 'SOLID en ideas cortas', description: 'Cinco principios para reconocer responsabilidades, contratos y dependencias más claras.', minutes: 7, tags: ['SOLID','SRP','OCP','LSP','ISP','DIP'], objectives: ['Explicar los cinco principios de forma simple','Detectar un acoplamiento evitable','Relacionar un problema con una mejora pequeña'], prerequisites: ['u02-c'], resources: [java] },
  { id: 'u08-b', unitId: 5, title: 'Patrones de creación en pocas líneas', description: 'Singleton, Factory Method, Abstract Factory, Builder y Prototype, sin sobrediseñar.', minutes: 6, tags: ['patrones','Singleton','Factory Method','Abstract Factory','Builder','Prototype'], objectives: ['Reconocer una necesidad de creación','Distinguir fábrica de builder','Evitar abstracciones innecesarias'], prerequisites: ['u08-a'], resources: [java] },
  { id: 'u08-c', unitId: 5, title: 'Patrones para conectar y variar comportamientos', description: 'Adapter, Facade, Proxy, Decorator, Strategy y Observer con Java mínimo.', minutes: 7, tags: ['patrones','Adapter','Facade','Proxy','Decorator','Strategy','Observer'], objectives: ['Distinguir la intención de patrones comunes','Reconocer composición y delegación','Explicar un límite de cada patrón'], prerequisites: ['u08-b'], resources: [java] },
  { id: 'u05-a', unitId: 6, title: 'Excepciones que explican lo que falló', description: 'Checked, unchecked y propagación sin ocultar la causa del error.', minutes: 7, tags: ['exceptions','checked','unchecked','throw','throws'], objectives: ['Clasificar excepciones','Preservar la causa','Elegir dónde recuperar o propagar'], prerequisites: ['u02-c'], resources: [java] },
  { id: 'u05-b', unitId: 6, title: 'Cerrar recursos correctamente', description: 'Try-with-resources, AutoCloseable y fallos durante el cierre.', minutes: 6, tags: ['try-with-resources','AutoCloseable','finally','suppressed'], objectives: ['Cerrar recursos aun si hay errores','Explicar orden de cierre','Reconocer excepciones suprimidas'], prerequisites: ['u05-a'], resources: [java] },
  { id: 'u05-c', unitId: 6, title: 'Archivos con Path y Files', description: 'Lectura y escritura explícitas, streaming y rutas controladas.', minutes: 8, tags: ['NIO','Files','Path','UTF-8','archivos'], objectives: ['Leer archivos según su tamaño','Escribir texto con encoding explícito','Validar rutas y errores de acceso'], prerequisites: ['u05-b'], resources: [java] },
  { id: 'u06-a', unitId: 7, title: 'Lambdas e interfaces funcionales', description: 'Pasá comportamiento como dato y componé reglas fáciles de probar.', minutes: 7, tags: ['lambda','Predicate','Function','Supplier','Consumer'], objectives: ['Identificar una interfaz funcional','Elegir un contrato funcional','Componer predicados'], prerequisites: ['u03-b'], resources: [java] },
  { id: 'u06-b', unitId: 7, title: 'Streams y collectors paso a paso', description: 'Filtrá, transformá y agrupá pedidos sin mezclar cálculo y efectos.', minutes: 9, tags: ['Stream','collectors','map','flatMap','reduce'], objectives: ['Separar operaciones intermedias y terminales','Agrupar y sumar datos','Evitar efectos compartidos'], prerequisites: ['u06-a'], resources: [java] },
  { id: 'u06-c', unitId: 7, title: 'Optional y fechas sin ambigüedades', description: 'Representá ausencias e instantes usando los tipos que corresponden.', minutes: 8, tags: ['Optional','Instant','LocalDate','ZoneId','Clock'], objectives: ['Componer Optional sin get inseguro','Distinguir fecha de instante','Escribir lógica temporal comprobable'], prerequisites: ['u06-a'], resources: [java] },
  { id: 'u07-a', unitId: 8, title: 'Java 8, 17 y 21: anotaciones, records y Lombok', description: 'Reconocé qué aporta cada herramienta sin confundir metadatos con comportamiento.', minutes: 8, tags: ['Java 21','Java 17','annotations','records','Lombok'], objectives: ['Entender retención y procesamiento de anotaciones','Elegir records o clases','Identificar prestaciones por versión'], prerequisites: ['u02-c'], resources: [java] },
  { id: 'u07-b', unitId: 8, title: 'Concurrencia y estado compartido', description: 'Hilos, executors y las diferencias entre visibilidad y atomicidad.', minutes: 9, tags: ['threads','executors','synchronized','volatile','race condition'], objectives: ['Detectar una condición de carrera','Proteger operaciones compuestas','Gestionar el ciclo de un executor'], prerequisites: ['u05-b'], resources: [java] },
  { id: 'u07-c', unitId: 8, title: 'CompletableFuture y virtual threads', description: 'Coordiná tareas y entendé cuándo la concurrencia mejora el throughput.', minutes: 9, tags: ['CompletableFuture','virtual threads','timeouts','concurrencia'], objectives: ['Combinar resultados asíncronos','Gestionar errores y límites','Elegir hilos virtuales para I/O'], prerequisites: ['u07-b'], resources: [java] },
];
