import type { QuizQuestion } from '../types';

type Spec = [string, number, string, string, number, string[], string];

function quiz([id, unitId, lessonId, prompt, correctIndex, texts, correctExplanation]: Spec): QuizQuestion {
  return {
    id: `quiz-extra-${id}`,
    unitId,
    lessonId,
    prompt,
    correctIndex,
    options: texts.map((text, index) => ({
      text,
      explanation: index === correctIndex
        ? `Correcta: ${correctExplanation}`
        : 'No es correcta: no describe el comportamiento pedido en este caso.',
    })),
  };
}

const specs: Spec[] = [
  ['u1-jdk', 1, 'u01-a', '¿Qué incluye un JDK además de la JVM?', 1, ['Solo clases de tu aplicación', 'Herramientas como javac y utilidades de desarrollo', 'Únicamente el garbage collector', 'Un servidor HTTP incorporado'], 'el JDK aporta compilador y herramientas para desarrollar y ejecutar Java.'],
  ['u1-bytecode', 1, 'u01-a', '¿Qué produce javac al compilar una clase Java?', 2, ['Código máquina específico del procesador', 'Un archivo Docker listo para ejecutar', 'Bytecode que ejecuta la JVM', 'Una consulta SQL optimizada'], 'javac genera bytecode, que la JVM interpreta o compila en tiempo de ejecución.'],
  ['u1-dependency', 1, 'u01-a', '¿Para qué sirve declarar una dependencia en Maven?', 0, ['Para resolver una biblioteca y su versión de forma reproducible', 'Para crear una rama Git automáticamente', 'Para convertir Java a JavaScript', 'Para ocultar errores de compilación'], 'Maven resuelve dependencias declaradas y ayuda a repetir el build en otro entorno.'],
  ['u1-status', 1, 'u01-b', '¿Qué muestra git status?', 3, ['El historial completo del remoto', 'La configuración del compilador Java', 'Solo los commits ya publicados', 'Cambios del directorio, área de preparación y rama actual'], 'permite ver qué cambios faltan preparar, confirmar o revisar antes de seguir.'],
  ['u1-commit', 1, 'u01-b', '¿Qué representa mejor un commit pequeño?', 1, ['Un respaldo de toda la computadora', 'Un cambio coherente que se puede revisar y revertir', 'Una rama que nunca se mezcla', 'Un despliegue automático a producción'], 'un commit enfocado facilita revisión, diagnóstico y reversión de una intención concreta.'],
  ['u1-conflict', 1, 'u01-b', 'Al resolver un conflicto de Git, ¿qué paso es esencial?', 2, ['Borrar ambos cambios sin leerlos', 'Ejecutar git push antes de editar', 'Entender la intención de ambas versiones y probar el resultado', 'Cambiar siempre a la rama main'], 'un conflicto se resuelve integrando la intención correcta y comprobando que el código sigue funcionando.'],
  ['u1-semver', 1, 'u01-c', 'En versionado semántico, ¿cuándo aumenta la versión major?', 0, ['Cuando hay un cambio incompatible para consumidores', 'Al corregir una errata de documentación', 'Al agregar una mejora compatible', 'En cada commit de una rama local'], 'la versión major comunica que clientes pueden necesitar adaptar su integración.'],
  ['u1-scrum', 1, 'u01-c', '¿Cuál es el objetivo central de un Sprint en Scrum?', 3, ['Asignar tareas individuales sin revisión', 'Medir horas trabajadas por persona', 'Evitar cambios de requisitos para siempre', 'Producir un incremento útil hacia un objetivo acordado'], 'el Sprint busca crear valor verificable mediante un incremento, no solo completar actividad.'],

  ['u2-string-equals', 2, 'u02-a', '¿Cómo comparás el contenido de dos String en Java?', 1, ['Con == siempre', 'Con equals, idealmente sobre un literal si puede haber null', 'Comparando hashCode únicamente', 'Con toString en ambos valores'], 'equals compara contenido; == compara identidad de referencias.'],
  ['u2-unboxing', 2, 'u02-a', '¿Qué riesgo tiene deshacer boxing de un Integer null a int?', 2, ['Java lo convierte automáticamente a cero', 'Se crea una copia profunda del objeto', 'Se lanza NullPointerException', 'El compilador cambia int por long'], 'el unboxing necesita un valor real y falla cuando la referencia wrapper es null.'],
  ['u2-constructor', 2, 'u02-b', '¿Qué responsabilidad tiene un constructor bien diseñado?', 0, ['Dejar el objeto en un estado válido al crearlo', 'Persistir siempre el objeto en base de datos', 'Evitar todo método público', 'Reemplazar una interfaz'], 'el constructor recibe dependencias o datos iniciales y protege invariantes desde el nacimiento del objeto.'],
  ['u2-encapsulation', 2, 'u02-b', '¿Qué aporta encapsular el saldo de una cuenta?', 3, ['Permite modificarlo desde cualquier clase', 'Elimina la necesidad de reglas de negocio', 'Hace que la clase sea automáticamente inmutable', 'Centraliza las reglas que protegen cambios válidos'], 'los métodos de dominio controlan que cada modificación respete las reglas de la cuenta.'],
  ['u2-static', 2, 'u02-b', '¿Cuándo conviene un miembro static?', 1, ['Cuando cada objeto necesita un valor distinto', 'Cuando el dato o comportamiento pertenece a la clase, no a una instancia', 'Para resolver cualquier problema concurrente', 'Para reemplazar constructores privados'], 'static representa estado o comportamiento compartido por la clase completa.'],
  ['u2-overload', 2, 'u02-c', '¿Qué diferencia una sobrecarga de una sobrescritura?', 2, ['La sobrecarga solo existe en interfaces', 'La sobrescritura cambia el nombre del método', 'La sobrecarga cambia parámetros; la sobrescritura redefine comportamiento heredado', 'No hay diferencia en Java'], 'la sobrecarga se resuelve por firma y la sobrescritura participa del polimorfismo.'],
  ['u2-abstract', 2, 'u02-c', '¿Cuándo elegir una clase abstracta antes que una interfaz?', 0, ['Cuando varias implementaciones comparten estado o comportamiento base', 'Cuando necesitás implementar múltiples contratos', 'Cuando no querés permitir herencia', 'Cuando el tipo no tiene comportamiento'], 'una clase abstracta permite compartir implementación y estado común entre subtipos relacionados.'],
  ['u2-polymorphism', 2, 'u02-c', '¿Qué permite el polimorfismo?', 3, ['Acceder a campos privados desde cualquier lado', 'Cambiar el tipo real de un objeto en memoria', 'Evitar usar contratos', 'Usar una abstracción y variar la implementación concreta'], 'el consumidor depende del contrato y puede recibir implementaciones intercambiables.'],

  ['u3-list', 3, 'u03-a', '¿Qué colección elegirías para conservar orden e incluir duplicados?', 1, ['Set', 'List', 'Map', 'PriorityQueue'], 'List conserva una secuencia y permite elementos repetidos.'],
  ['u3-set', 3, 'u03-a', '¿Qué propiedad es propia de un Set?', 2, ['Garantiza acceso por índice', 'Asocia una clave a un valor', 'No admite elementos duplicados según igualdad', 'Siempre conserva orden de inserción'], 'un Set representa pertenencia y descarta duplicados de acuerdo con equals y hashCode.'],
  ['u3-map', 3, 'u03-a', '¿Qué operación expresa mejor un Map?', 0, ['Buscar un valor a partir de una clave', 'Insertar solo valores sin referencia', 'Ordenar todos los elementos automáticamente', 'Ejecutar tareas en paralelo'], 'Map modela asociaciones clave-valor para recuperar información por una clave.'],
  ['u3-pecs', 3, 'u03-b', '¿Qué resume la regla PECS para wildcards?', 3, ['Producer Extends, Consumer Super', 'Private Encapsulation Creates Safety', 'Pointers Enable Concurrent Streams', 'Public Equals Compares Strings'], 'una fuente que produce usa extends; un destino que consume usa super.'],
  ['u3-invariance', 3, 'u03-b', '¿Por qué List<Integer> no es subtipo de List<Number>?', 1, ['Porque Integer no extiende Number', 'Porque los genéricos de Java son invariantes', 'Porque las listas no admiten números', 'Porque Number es una interfaz'], 'la invariancia evita insertar otro subtipo de Number en una lista solo de Integer.'],
  ['u3-erasure', 3, 'u03-b', '¿Qué consecuencia tiene type erasure?', 2, ['Los genéricos se verifican solo en producción', 'Las listas dejan de almacenar objetos', 'No se puede crear directamente un array de T en código genérico usual', 'Toda clase genérica debe ser abstracta'], 'la información genérica se borra en gran parte al runtime y limita ciertas operaciones.'],
  ['u3-comparable', 3, 'u03-c', '¿Qué define Comparable<T> en un tipo?', 0, ['Su orden natural mediante compareTo', 'Su igualdad mediante hashCode', 'Su serialización JSON', 'Su ciclo de vida en Spring'], 'Comparable incorpora un criterio natural del propio tipo cuando ese orden tiene sentido estable.'],
  ['u3-tree-set', 3, 'u03-c', '¿Qué cuidado requiere un TreeSet frente a Comparator?', 3, ['Que Comparator nunca devuelva cero', 'Que use solamente campos static', 'Que reemplace equals en todas las clases', 'Que el orden sea consistente para no tratar valores distintos como iguales'], 'si compare devuelve cero, TreeSet puede considerar duplicados aunque equals difiera.'],

  ['u4-big-o', 4, 'u04-a', '¿Qué describe Big O principalmente?', 1, ['El tiempo exacto en milisegundos', 'Cómo crece el costo al crecer la entrada', 'La cantidad exacta de líneas de código', 'El lenguaje usado para implementar'], 'Big O expresa una tendencia de crecimiento y permite comparar enfoques a escala.'],
  ['u4-binary-search', 4, 'u04-a', '¿Qué precondición necesita búsqueda binaria?', 2, ['Una lista con duplicados', 'Un HashMap auxiliar', 'Datos ordenados según el mismo criterio', 'Un árbol balanceado'], 'la decisión de descartar una mitad solo es válida si el orden conocido se mantiene.'],
  ['u4-stability', 4, 'u04-b', '¿Qué significa que un ordenamiento sea estable?', 0, ['Conserva el orden relativo de elementos con misma clave', 'Nunca usa memoria adicional', 'Siempre cuesta O(n log n)', 'No compara elementos iguales'], 'la estabilidad importa cuando un orden previo también tiene significado para elementos empatados.'],
  ['u4-quicksort', 4, 'u04-b', '¿Cuál es el costo promedio habitual de quicksort?', 3, ['O(1)', 'O(n)', 'O(n²) en todos los casos', 'O(n log n)'], 'una partición razonable produce el costo promedio O(n log n), aunque existe peor caso cuadrático.'],
  ['u4-recursion', 4, 'u04-c', '¿Para qué sirve el caso base de una recursión?', 1, ['Para llamar al método con la misma entrada', 'Para detener llamadas y devolver una solución directa', 'Para crear siempre un hilo nuevo', 'Para ordenar la pila de ejecución'], 'sin caso base alcanzable, la recursión no termina y puede agotar el stack.'],
  ['u4-heap', 4, 'u04-c', '¿Qué permite obtener eficientemente un heap?', 2, ['El elemento central de un array', 'Todos los elementos ordenados por iteración', 'El mínimo o máximo según su configuración', 'Una clave por nombre'], 'un heap prioriza su cabeza; no ofrece una iteración completamente ordenada.'],
  ['u4-two-pointers', 4, 'u04-d', '¿Qué ventaja tiene two pointers sobre probar todos los pares?', 0, ['Puede recorrer una estructura en una pasada con invariantes claras', 'Obliga a usar recursión', 'Siempre elimina la necesidad de ordenar', 'Convierte todo problema en O(1)'], 'los punteros evitan reiniciar comparaciones y suelen lograr costo lineal según la precondición.'],

  ['u5-srp', 5, 'u08-a', '¿Qué busca el principio de responsabilidad única?', 1, ['Que una clase tenga un solo método', 'Que una clase tenga una razón coherente para cambiar', 'Que todas las clases sean final', 'Que no existan dependencias'], 'SRP agrupa responsabilidades relacionadas y reduce cambios por motivos independientes.'],
  ['u5-ocp', 5, 'u08-a', '¿Qué propone abierto/cerrado de SOLID?', 2, ['Nunca editar código existente', 'Evitar toda herencia', 'Extender comportamiento sin modificar cada consumidor estable', 'Crear una clase por condición if'], 'se buscan puntos de extensión razonables, no una abstracción prematura para todo caso posible.'],
  ['u5-lsp', 5, 'u08-a', '¿Qué se rompe si un subtipo no cumple expectativas del contrato base?', 0, ['Sustitución de Liskov', 'La compilación de Maven', 'El orden natural del tipo', 'La existencia de un constructor'], 'un subtipo debe poder usarse donde se espera el tipo base sin sorprender al consumidor.'],
  ['u5-isp', 5, 'u08-a', '¿Qué evita el principio de segregación de interfaces?', 3, ['Tener varios métodos privados', 'Usar interfaces funcionales', 'Crear DTOs', 'Forzar clientes a depender de operaciones que no usan'], 'interfaces pequeñas y enfocadas reducen acoplamiento y métodos irrelevantes para clientes.'],
  ['u5-builder', 5, 'u08-b', '¿Cuándo aporta claridad Builder?', 1, ['Cuando un objeto no tiene campos', 'Cuando construirlo requiere varios valores opcionales o legibles', 'Para reemplazar cualquier factory', 'Cuando siempre debe existir una sola instancia'], 'Builder hace explícita una creación con opciones y evita constructores largos poco comprensibles.'],
  ['u5-factory', 5, 'u08-b', '¿Qué problema resuelve una Factory Method?', 2, ['Agregar comportamiento a un objeto existente', 'Traducir una interfaz incompatible', 'Centralizar la elección o creación de una implementación', 'Notificar muchos observadores'], 'la fábrica separa al consumidor de detalles concretos de instanciación.'],
  ['u5-adapter', 5, 'u08-c', '¿Para qué usarías Adapter?', 0, ['Para adaptar una interfaz existente al contrato que necesita tu aplicación', 'Para crear copias profundas de objetos', 'Para imponer una sola instancia', 'Para ordenar colecciones'], 'Adapter traduce contratos y evita que detalles externos invadan el modelo interno.'],
  ['u5-observer', 5, 'u08-c', '¿Qué relación modela Observer?', 3, ['Una clase que hereda de todas las demás', 'Una colección ordenada de claves', 'Una instancia global compartida', 'Un cambio que notifica a interesados desacoplados'], 'Observer permite publicar una señal a suscriptores sin que el emisor conozca sus detalles.'],

  ['u6-checked', 6, 'u05-a', '¿Qué criterio ayuda a elegir una checked exception?', 0, ['Que el llamador puede recuperar o debe reconocer la situación', 'Que toda excepción debe ser checked', 'Que el error nunca se propaga', 'Que sustituye la validación de argumentos'], 'las checked fuerzan a considerar fallos recuperables o relevantes en el contrato.'],
  ['u6-cause', 6, 'u05-a', '¿Por qué conservar la causa al envolver una excepción?', 1, ['Para ocultar el error original', 'Para mantener evidencia del fallo inicial y su cadena', 'Para evitar cualquier log', 'Para convertir todo fallo en null'], 'la causa permite diagnosticar el origen sin perder contexto al traducir una frontera.'],
  ['u6-unchecked', 6, 'u05-a', '¿Qué suele indicar IllegalArgumentException?', 2, ['Que un archivo fue cerrado correctamente', 'Que el compilador no encontró una clase', 'Que un argumento viola una precondición del método', 'Que la red respondió un código HTTP'], 'indica que el consumidor pasó un valor inválido para el contrato local.'],
  ['u6-twr-order', 6, 'u05-b', '¿En qué orden cierra try-with-resources varios recursos?', 3, ['En el orden en que fueron declarados', 'En orden alfabético por variable', 'Solo cierra el último recurso', 'En orden inverso a su declaración'], 'cerrar en orden inverso permite liberar primero el recurso que depende de otro anterior.'],
  ['u6-suppressed', 6, 'u05-b', '¿Qué ocurre si falla el cuerpo y también el cierre de un recurso?', 1, ['Se pierden ambos errores', 'El error de cierre puede quedar como excepción suprimida', 'Java reinicia automáticamente el bloque', 'El recurso queda abierto por definición'], 'try-with-resources preserva el fallo principal y adjunta fallos de cierre como suprimidos.'],
  ['u6-path', 6, 'u05-c', '¿Qué representa Path en NIO?', 0, ['Una ruta como objeto que puede resolverse y normalizarse', 'El contenido completo de un archivo', 'Una conexión HTTP abierta', 'Una excepción checked'], 'Path modela la ubicación; Files aporta operaciones para leer, escribir y consultar.'],
  ['u6-encoding', 6, 'u05-c', '¿Por qué declarar UTF-8 al escribir texto?', 2, ['Para comprimir cualquier archivo', 'Para impedir que haya saltos de línea', 'Para evitar ambigüedad sobre cómo convertir caracteres a bytes', 'Para hacer que Files sea thread-safe'], 'indicar encoding hace el formato reproducible entre equipos y entornos distintos.'],
  ['u6-large-file', 6, 'u05-c', '¿Qué enfoque conviene para procesar un archivo muy grande?', 3, ['Leer todo con readString sin evaluar tamaño', 'Convertirlo primero a Base64', 'Abrirlo con una GUI obligatoriamente', 'Procesarlo en stream y cerrar el recurso al terminar'], 'un flujo reduce memoria retenida y try-with-resources garantiza el cierre del archivo.'],

  ['u7-predicate', 7, 'u06-a', '¿Qué expresa Predicate<T>?', 1, ['Una transformación T a R', 'Una condición que recibe T y devuelve boolean', 'Un proveedor sin salida', 'Una acción que devuelve Optional'], 'Predicate modela una regla de verdad, útil para filtrar o validar valores.'],
  ['u7-function', 7, 'u06-a', '¿Qué expresa Function<T, R>?', 2, ['Una acción sin retorno', 'Una condición booleana', 'Una transformación de T hacia R', 'Un valor constante sin entrada'], 'Function representa una transformación que puede usarse con map y composición.'],
  ['u7-supplier', 7, 'u06-a', '¿Cuándo elegir Supplier<T>?', 0, ['Cuando necesitás obtener un valor sin recibir argumento', 'Cuando necesitás comparar dos objetos', 'Cuando querés cerrar un recurso', 'Cuando necesitás dos parámetros'], 'Supplier representa producción diferida de un valor y se usa en fallbacks o factories.'],
  ['u7-map-flatmap', 7, 'u06-b', '¿Cuándo usar flatMap en un Stream?', 3, ['Para ordenar siempre una colección', 'Para ejecutar efectos secundarios', 'Para convertir todos los elementos en boolean', 'Para aplanar resultados que contienen varios elementos o streams'], 'flatMap evita obtener una estructura anidada cuando cada elemento produce varios resultados.'],
  ['u7-collectors', 7, 'u06-b', '¿Qué permite Collectors.groupingBy?', 1, ['Cerrar la colección original', 'Agrupar elementos según una clave calculada', 'Paralelizar cualquier Stream sin costo', 'Modificar todos los objetos fuente'], 'groupingBy construye una agrupación declarativa a partir de una función de clasificación.'],
  ['u7-stream-side-effect', 7, 'u06-b', '¿Qué práctica conviene evitar dentro de map?', 2, ['Transformar un valor a otro', 'Usar una referencia a método clara', 'Mutar estado externo compartido', 'Componer transformaciones puras'], 'los efectos compartidos dificultan razonar sobre orden, pruebas y posibles ejecuciones paralelas.'],
  ['u7-optional-get', 7, 'u06-c', '¿Por qué Optional.get suele ser una mala opción pública?', 0, ['Porque falla si el valor está ausente sin expresar una alternativa', 'Porque siempre crea una copia del valor', 'Porque transforma el valor en null', 'Porque solo existe desde Java 21'], 'orElseGet, map u orElseThrow documentan mejor qué hacer ante una ausencia.'],
  ['u7-clock', 7, 'u06-c', '¿Qué aporta inyectar Clock en lógica temporal?', 3, ['Hace que el tiempo sea más rápido', 'Convierte Instant en String automáticamente', 'Elimina las zonas horarias', 'Permite controlar el tiempo en pruebas sin depender del reloj real'], 'Clock vuelve reproducibles las pruebas de fechas y evita depender de la hora actual del sistema.'],

  ['u8-record', 8, 'u07-a', '¿Para qué encaja mejor un record?', 1, ['Para una entidad JPA mutable con ciclo de vida complejo', 'Para transportar datos con componentes y valor semántico claro', 'Para reemplazar toda interfaz funcional', 'Para sincronizar acceso concurrente'], 'un record reduce boilerplate de datos y expresa un tipo principalmente portador de valores.'],
  ['u8-annotation-retention', 8, 'u07-a', '¿Qué define la retención de una anotación?', 2, ['El nombre visible en un IDE', 'La cantidad de métodos anotados', 'Hasta qué fase existe: fuente, class o runtime', 'El orden de las dependencias Maven'], 'Retention determina si herramientas o reflexión pueden observar la anotación en ejecución.'],
  ['u8-lombok', 8, 'u07-a', '¿Qué cuidado requiere Lombok?', 0, ['Entender el código generado y no ocultar contratos importantes', 'Usarlo para administrar conexiones JDBC', 'Suponer que evita toda prueba', 'Reemplazar el compilador de Java'], 'Lombok reduce repetición, pero el equipo debe entender métodos, constructores y mutabilidad que genera.'],
  ['u8-volatile', 8, 'u07-b', '¿Qué garantiza volatile principalmente?', 3, ['Atomicidad de contador++', 'Exclusión mutua entre hilos', 'Orden total de todas las operaciones', 'Visibilidad de una escritura entre hilos'], 'volatile ayuda a observar cambios, pero no protege operaciones compuestas de lectura y escritura.'],
  ['u8-synchronized', 8, 'u07-b', '¿Qué aporta synchronized alrededor de una operación compuesta?', 1, ['Convierte el método en asíncrono', 'Exclusión mutua y visibilidad al usar el mismo monitor', 'Evita toda espera de I/O', 'Crea una copia inmutable del objeto'], 'sincronizar correctamente protege una sección crítica frente a carreras sobre estado compartido.'],
  ['u8-executor', 8, 'u07-b', '¿Por qué usar ExecutorService en vez de crear hilos sin límite?', 2, ['Porque impide toda concurrencia', 'Porque ejecuta siempre en un único hilo', 'Porque permite controlar recursos, cola y ciclo de vida de tareas', 'Porque elimina errores de red'], 'un executor hace explícitos los límites y facilita apagar o supervisar el trabajo.'],
  ['u8-completable-future', 8, 'u07-c', '¿Qué permite combinar dos resultados independientes con CompletableFuture?', 0, ['Coordinar ambas tareas sin bloquear manualmente cada resultado', 'Convertir automáticamente una tarea en transacción', 'Evitar definir timeouts', 'Hacer seguro cualquier estado mutable'], 'las combinaciones declaran dependencias entre resultados, pero aún requieren límites y manejo de errores.'],
  ['u8-virtual-thread-limit', 8, 'u07-c', '¿Qué límite sigue existiendo con virtual threads?', 3, ['La JVM solo permite diez tareas', 'No pueden realizar I/O', 'No usan memoria alguna', 'Las conexiones y dependencias externas siguen teniendo capacidad finita'], 'los hilos son más livianos, pero bases, APIs y pools externos aún necesitan límites.'],
];

export const foundationExpansionQuizzes: QuizQuestion[] = specs.map(quiz);
