export const glossary = [
 ['JDK','Kit para desarrollar Java: compilador, herramientas y entorno de ejecución.','Java'],
 ['JVM','Máquina virtual que ejecuta bytecode; gestiona memoria y puede compilar código con JIT.','Java'],
 ['Inmutabilidad','Un objeto no cambia su estado observable después de construirse. Un record no vuelve inmutables sus referencias internas.','Java'],
 ['Contrato equals/hashCode','Objetos iguales deben tener el mismo hash. El hash igual por sí solo no implica igualdad.','Colecciones'],
 ['Generics','Parámetros de tipo que permiten reutilizar código conservando comprobaciones de tipo en compilación.','Java'],
 ['Heap','En estructuras de datos: árbol con prioridad en la raíz. En JVM: región de memoria para objetos. Son conceptos distintos.','Algoritmos'],
 ['Big O','Cota asintótica del crecimiento del costo temporal o espacial al aumentar la entrada. No mide segundos.','Algoritmos'],
 ['Stream','Secuencia de operaciones sobre datos, habitualmente perezosa hasta una operación terminal. No almacena los datos.','Java'],
 ['Optional','Contenedor para expresar presencia o ausencia de un resultado. Evitá usar get() sin justificar la presencia.','Java'],
 ['Condición de carrera','El resultado depende del orden no controlado de accesos concurrentes a un estado compartido.','Concurrencia'],
 ['IoC / DI','Inversión de control: el contenedor gestiona objetos. Inyección de dependencias: reciben sus colaboradores desde afuera.','Spring'],
 ['Bean','Objeto administrado por el contenedor Spring. El scope singleton es por definición de bean y contenedor.','Spring'],
 ['DTO','Objeto que define los datos de entrada o salida de una operación; separa el contrato externo del modelo persistente.','APIs'],
 ['Idempotencia','Repetir una operación tiene el mismo efecto previsto que realizarla una vez; no obliga a devolver idéntica respuesta.','APIs'],
 ['Serialización','Transformar un objeto en una representación transportable como JSON. Deserializar realiza el proceso inverso.','APIs'],
 ['ORM','Herramienta que relaciona objetos con tablas. No elimina la necesidad de comprender SQL.','Persistencia'],
 ['N+1','Una consulta inicial seguida por una consulta adicional por cada resultado al acceder a relaciones.','Persistencia'],
 ['Transacción','Conjunto de operaciones con límites de atomicidad y consistencia, sujeto al aislamiento configurado.','Persistencia'],
 ['Lock optimista','Detecta modificaciones concurrentes, normalmente comparando una versión, en lugar de bloquear anticipadamente.','Persistencia'],
 ['Mock','Doble de prueba configurado para simular respuestas y, cuando corresponde, verificar interacciones.','Testing'],
 ['Cobertura','Medida de código ejecutado durante pruebas. Un porcentaje alto no garantiza buenas aserciones.','Testing'],
 ['Puerto y adaptador','Un puerto expresa un contrato de la aplicación. Un adaptador conecta ese contrato con una tecnología externa.','Arquitectura'],
 ['Agregado','Frontera de consistencia de un modelo de dominio, controlada por su entidad raíz.','DDD'],
 ['Bounded context','Límite dentro del cual un modelo y sus términos tienen un significado coherente.','DDD'],
 ['Consumer group','Grupo de consumidores Kafka que se reparten particiones. Grupos distintos mantienen su propio progreso.','Kafka'],
 ['Offset','Posición de un registro dentro de una partición Kafka; no es un identificador global de todos los mensajes.','Kafka'],
 ['Broker','Nodo de Kafka que almacena registros de forma persistente y atiende a productores y consumidores.','Kafka'],
 ['Clúster Kafka','Conjunto de brokers que comparte metadatos y distribuye topics, réplicas y carga.','Kafka'],
 ['Topic','Canal lógico de registros Kafka, dividido en una o más particiones.','Kafka'],
 ['Partición','Subdivisión ordenada de un topic. El orden solo está garantizado dentro de una misma partición.','Kafka'],
 ['Producer','Cliente que publica registros en un topic; una key puede dirigir registros relacionados a la misma partición.','Kafka'],
 ['Consumer','Cliente que lee registros de Kafka y controla su ritmo de consumo mediante polling.','Kafka'],
 ['Replication factor','Cantidad total de copias de cada partición, incluida la réplica líder. Aumenta tolerancia a fallos y costo.','Kafka'],
 ['ISR','In-Sync Replicas: conjunto de réplicas suficientemente al día con el líder de una partición.','Kafka'],
 ['Leader y follower','El líder de una partición atiende lecturas y escrituras; los followers replican sus registros y pueden asumir el liderazgo.','Kafka'],
 ['Retención','Política que elimina registros Kafka por tiempo o tamaño, aunque ya hayan sido consumidos.','Kafka'],
 ['Compactación de log','Política que conserva al menos el último valor conocido por key; no mantiene cada evento histórico.','Kafka'],
 ['Tombstone','Registro con key y valor nulo en un topic compactado, que marca esa key para su eliminación posterior.','Kafka'],
 ['Lag','Diferencia entre el último offset disponible y el offset ya procesado o confirmado por un consumer group.','Kafka'],
 ['Rebalanceo','Redistribución de particiones entre consumidores de un grupo al cambiar sus miembros o su suscripción.','Kafka'],
 ['acks','Configuración del producer sobre cuándo confirma un envío: 0 no espera, 1 espera al líder y all espera al ISR requerido.','Kafka'],
 ['Serializer','Componente del producer que convierte una key o valor de aplicación en bytes para Kafka.','Kafka'],
 ['Deserializer','Componente del consumer que reconstruye una key o valor desde bytes; debe concordar con el formato publicado.','Kafka'],
 ['KafkaTemplate','Abstracción de Spring Kafka para enviar registros mediante el producer configurado.','Spring Kafka'],
 ['@KafkaListener','Anotación de Spring Kafka que declara un método consumidor y configura su suscripción mediante un listener container.','Spring Kafka'],
 ['ZooKeeper','Servicio externo usado por versiones históricas de Kafka para coordinar metadatos. Los clústeres modernos usan KRaft.','Kafka'],
 ['KRaft','Modo de Kafka que administra sus metadatos con un quórum Raft interno, sin depender de ZooKeeper.','Kafka'],
 ['DLQ','Dead Letter Queue: topic para registros que no pueden procesarse tras la política de reintentos definida.','Kafka'],
 ['Dead letter','Registro enviado a una DLQ para aislar un fallo y permitir análisis o reproceso sin bloquear el flujo principal.','Kafka'],
 ['Outbox','Registro transaccional del cambio de negocio y un evento pendiente, que otro proceso publica posteriormente.','Distribuidos'],
 ['Consistencia eventual','Las réplicas o proyecciones convergen con el tiempo si se cumplen las condiciones del sistema. Hay una ventana de desfase.','Distribuidos'],
 ['Observabilidad','Capacidad de inferir el estado del sistema a partir de señales como logs, métricas y trazas.','Operación'],
 ['JWT','Formato de token con claims. Un token firmado normalmente no cifra su contenido ni resuelve la revocación por sí solo.','Seguridad'],
 ['Circuit breaker','Mecanismo que suspende llamadas a un destino con fallos y luego prueba su recuperación.','Resiliencia'],
 ['TTL','Tiempo de vida de un dato en caché. Reduce antigüedad pero no garantiza consistencia inmediata.','Caché'],
 ['Debugger','Herramienta para detener una ejecución, inspeccionar estado y comprobar una hipótesis sobre un fallo.','Herramientas'],
 ['Breakpoint','Punto de pausa de un debugger; puede condicionarse para evitar detenerse en cada iteración.','Herramientas'],
 ['Stack trace','Cadena de llamadas de una excepción. La causa más profunda y el primer marco propio ayudan a investigar.','Herramientas'],
 ['JAVA_HOME','Variable que identifica la instalación de JDK elegida por una herramienta. No debe contener secretos.','Herramientas'],
 ['Heap JVM','Región de memoria administrada donde viven objetos. No es el heap usado como estructura de datos.','Java'],
 ['Garbage collector','Componente de la JVM que recupera objetos inalcanzables; no elimina referencias retenidas por error.','Java'],
 ['Fuga de memoria','Retención de objetos que el programa ya no necesita pero que siguen siendo alcanzables.','Java'],
 ['Copia defensiva','Copia de un dato mutable en una frontera para que cambios externos no rompan invariantes internas.','Java'],
 ['Cursor de paginación','Valor opaco que permite continuar una consulta ordenada desde una posición estable del recorrido.','APIs'],
 ['Migración de esquema','Cambio versionado y reproducible de una base de datos, aplicado en un orden controlado.','Persistencia'],
 ['Testcontainers','Biblioteca de pruebas que inicia dependencias efímeras, como PostgreSQL o Kafka, en contenedores.','Testing'],
 ['Readiness','Señal de que una instancia está preparada para recibir tráfico útil, no solo de que su proceso vive.','Operación'],
 ['Liveness','Señal de que el proceso sigue ejecutándose y puede requerir reinicio si falla. No confirma que pueda recibir tráfico.','Operación'],
 ['Graceful shutdown','Cierre que deja de aceptar trabajo nuevo y permite finalizar operaciones dentro de un límite antes de liberar recursos.','Operación'],
 ['ADR','Architecture Decision Record: documento breve que registra contexto, decisión, alternativas y consecuencias.','Arquitectura'],
 ['Timeout','Tiempo máximo de espera de una operación antes de considerarla fallida.','Resiliencia'],
 ['Backoff','Espera creciente o controlada entre reintentos para no sobrecargar una dependencia con problemas.','Resiliencia'],
 ['Bulkhead','Límite de concurrencia o recursos que evita que una dependencia lenta agote todo el servicio.','Resiliencia'],
 ['Cache stampede','Pico de consultas simultáneas a la fuente cuando una misma entrada de caché vence o falta.','Caché'],
 ['Schema Registry','Servicio que registra versiones de schemas y valida compatibilidad de contratos de eventos.','Kafka'],
 ['Avro','Formato y sistema de schema usado para serializar datos con evolución explícita de contratos.','Kafka'],
 ['Protobuf','Formato binario con schema definido mediante mensajes y campos versionables.','Kafka'],
 ['Compatibilidad de schema','Reglas que determinan si productores y consumidores de versiones diferentes pueden intercambiar eventos.','Kafka'],
 ['Retry topic','Topic dedicado a reintentos diferidos, separado del flujo principal de consumo.','Kafka'],
 ['SASL','Mecanismo de autenticación de clientes Kafka; se complementa con TLS y ACLs.','Kafka'],
 ['ACL','Regla de autorización que permite o deniega acciones de un principal sobre un recurso.','Seguridad'],
 ['Kafka Streams','Biblioteca para transformar, agrupar y unir streams Kafka con estado y ventanas de tiempo.','Kafka'],
] as const;

export const cheatSheets = [
 {title:'SQL Cheat Sheet',description:'Consultas, joins, agregaciones, transacciones e índices para repasar antes de una entrevista.',topic:'SQL',url:new URL('./cheatsheets/SQL-Cheatsheet.pdf',import.meta.url).href},
 {title:'Git Cheat Sheet',description:'Comandos y flujo de trabajo para ramas, cambios, conflictos y colaboración.',topic:'Git',url:new URL('./cheatsheets/Git-Cheatsheet.pdf',import.meta.url).href},
 {title:'Java 8 a 21 Cheat Sheet',description:'Características y APIs relevantes desde Java 8 hasta Java 21.',topic:'Java',url:new URL('./cheatsheets/Java-8-a-21-Cheatsheet.pdf',import.meta.url).href},
 {title:'SOLID y patrones Cheat Sheet',description:'Principios SOLID y patrones de diseño en una referencia breve.',topic:'Diseño',url:new URL('./cheatsheets/SOLID-y-Patrones-Cheatsheet.pdf',import.meta.url).href},
] as const;

export const labs=[
 {title:'Primer circuito Spring Boot + Kafka',description:'Publicá texto y JSON desde REST. Observá topics, particiones, offsets y grupos.',repository:'https://github.com/JonasGarcia1/springboot-kafka-roadmap-course',requirements:'Java 21, Maven, Docker y los puertos indicados en el README del repositorio.',steps:['Abrí el README del repositorio.','Levantá la infraestructura con Docker Compose según esa guía.','Iniciá learning-api y publicá un mensaje desde Swagger.','Sumá otra instancia del consumidor y observá el reparto de particiones.'],links:[{title:'Swagger de learning-api · local',url:'http://localhost:8080/swagger-ui/index.html'},{title:'Kafka UI · local',url:'http://localhost:8088'}],lessonId:'kafka-overview'},
 {title:'Kafka avanzado con límites explícitos',description:'Explorá idempotencia, transacciones, compactación y Kafka Streams sobre ejemplos aislados.',repository:'https://github.com/JonasGarcia1/springboot-kafka-roadmap-course/tree/main/advanced-labs',requirements:'Java 21, Maven y el entorno Docker del repositorio principal. Leé las advertencias de cada lección antes de ejecutar.',steps:['Abrí advanced-labs en el repositorio.','Compará producer idempotente con una transacción Kafka real.','Inspeccioná el topic compactado y sus keys.','Ejecutá las pruebas disponibles antes de probar el flujo manual.'],links:[{title:'Kafka UI · local',url:'http://localhost:8088'}],lessonId:'kafka-save-wikimedia'},
 {title:'Un pedido, dos consumidores',description:'Seguimiento de OrderCreatedEvent desde pedidos hacia inventario y notificaciones.',repository:'https://github.com/JonasGarcia1/springboot-kafka-order-events-lab',requirements:'Java 21, Maven y Docker. Usá los puertos del laboratorio para evitar conflictos con el otro proyecto.',steps:['Leé el README y la guía conceptual del repositorio.','Iniciá la infraestructura y los tres servicios según el README.','Creá un pedido y verificá inventario y notificaciones.','Repetí el mismo orderId y explicá por qué la deduplicación en memoria se pierde al reiniciar.'],links:[{title:'Swagger de pedidos · local',url:'http://localhost:8083/swagger-ui/index.html'},{title:'Kafka UI del laboratorio · local',url:'http://localhost:8089'}],lessonId:'u15-b'},
];
